// Edition timeline. Update when shipping a new edition.

export type ChangelogEntry = {
  edition: string;
  date: string;        // ISO yyyy-mm-dd
  tagline: string;
  shipped: string[];
  receipts?: { label: string; value: string }[];
  // Optional site-wide announcement bar. Set on the LATEST entry only.
  // bannerText = a short, scannable headline (≤ ~90 chars). bannerHref = where
  // "read more" points. The AnnouncementBar reads CHANGELOG[0]; dismissal is
  // keyed on `edition`, so a new edition auto-resurfaces the bar.
  bannerText?: string;
  bannerHref?: string;
};

export const CHANGELOG: ChangelogEntry[] = [
  {
    edition: 'Edition 14',
    date: '2026-09-05',
    tagline: 'The working edition. Find the right chapter, resume where you left off, and turn a task into a reviewable workflow specification.',
    bannerText: 'New: a searchable library, four learning paths, and the AI workflow planner.',
    bannerHref: '/library/',
    shipped: [
      'New library: chapters, selected guides, and tools with topic and format filters, plus four outcome-based reading paths.',
      'New workflow planner: four task presets, explicit inputs and approval boundaries, acceptance tests, and a downloadable Markdown specification. It plans a workflow; it does not execute one.',
      'Search, reading-history, and navigation fixes across client-side page transitions. Reading history stays in your browser.',
      'Corrections to setup instructions, scheduled-workflow recovery, research citations, and broken reference links.',
    ],
  },
  {
    edition: 'Edition 13',
    date: '2026-08-17',
    tagline: 'The queue edition. The swarm chapters taught running many sessions; this page is what those sessions should be fed. One GitHub Projects board per product family, issues written for an agent with no memory of the conversation that produced them, a pickup command that refuses vague specs, and a six-agent review fleet routed by file path — none of which gates a merge, all of which must be answered in writing. Installed across sixteen repos in one pass; fourteen went clean, and the four failure modes from the other two are on the page as rules the next install checks automatically. Screenshots are reconstructions with decoy repo names — the boards carry client work.',
    shipped: [
      'New page — /agent-workflow/. The five rules (one issue = one PR; the issue is the spec; the board answers "what can I start"; review before a human looks; nothing an agent says is a gate), the three slash commands (/task, /pick, /review), and the six-agent review fleet with path-glob routing a shell script can print and a human can audit.',
      'The full technical setup: plugin layout, the one committed JSON config per repo (deterministic checks + routing table), the board bootstrap that shapes GitHub Projects\' built-in Status field over GraphQL and reads it back, and the vendored board.sh — ready/queue/show/block over a shared multi-repo board.',
      'Every fork judged: board per repo vs shared per ecosystem, agents block vs inform, scripts vendored vs in-plugin, model tier per reviewer, solo vs team scope.',
      'The nightly pulse: a no-LLM scheduled job that writes boards, CI-on-main (newest run per workflow), open PRs, and a two-strike rule that turns a persistent red into a ready-to-run /task command. Signal becomes queued work or it evaporates.',
      'Failure receipts from the rollout: stray git hooks silently blocking commits for a week, a pre-push gate failing in a clean worktree, an LLM-judge CI check flaking on a config-only PR, and the Node 20-vs-26 glob mismatch that made a green local validation ship a red CI.',
    ],
    receipts: [
      { label: 'Repos on the workflow', value: '16' },
      { label: 'Review agents per branch', value: 'up to 6, path-routed' },
      { label: 'Clean installs first pass', value: '14/16' },
      { label: 'Setup time per new repo', value: '~10 min' },
    ],
  },
  {
    edition: 'Edition 12.1',
    date: '2026-08-17',
    tagline: 'The cockpit edition. Every chapter so far has been about what the agents do; this page is about the two square meters in front of the human. Run 6–8 Claude Code sessions in parallel and the bottleneck stops being the model — it\'s you, alt-tabbing through identical black rectangles, typing into the wrong one. Fleet paint is the fix: a statusline that names every session, OSC escape codes that recolor each window by project, and a launchd watcher that keeps the whole fleet painted automatically — one palette file that both the window and the badge read, so they can never disagree. Built by Claude Code across two evenings, including the one where it disassembled the terminal to check which escape codes actually work, and the second one — "harden it, no silent failures" — that turned a demo into infrastructure.',
    shipped: [
      'New page — /terminal-setup/. The four layers of terminal customization (app, prompt, escape codes, Claude Code itself) and which layer owns what; the honest terminal matrix — Terminal.app, iTerm2, WezTerm, Ghostty, kitty, Warp — including why Chapter 20\'s "skip Terminal.app" and this page\'s "it runs on Terminal.app" are both right.',
      'The out-of-the-box wins most people never turn on: /statusline (project, branch, context %, session cost under every prompt), custom Claude Code themes, /rename and the title bar as a status display, and terminal_bell → a silent Dock badge on the exact window that\'s waiting.',
      'Fleet paint, the full system: session registry maintained by hooks, an OKLCH-generated palette (6 hue families × 2 tiers, contrast and color-blindness validated by a generator that prints its proof), a ~1%-CPU launchd watcher painting each tty via OSC 10/11/12, and a statusline that reads the same palette — plus the seven gotchas that cost a day, from the 1 KiB pty write buffer to the terminal that reports its background as white.',
      'The build-it-with-Claude-Code section: the exact prompt shape, why it specifies the architecture but not the escape codes, and why "harden it — assume everything lies" is the instruction that separates a demo from a system. Reconstructured screenshots with decoy project names; the real fleet is client work.',
    ],
    receipts: [
      { label: 'Windows in the daily fleet', value: '5–8' },
      { label: 'Contrast the palette holds', value: '~15:1' },
      { label: 'Watcher CPU', value: '~1%' },
      { label: 'Evenings to build', value: '2' },
    ],
  },
  {
    edition: 'Edition 12.0',
    date: '2026-08-03',
    tagline: 'The physical edition. Every prior edition ran the loop on information; this one runs it on matter. Claude Code designed a wall frame for the bird station\'s 13.3" e-ink panel and its Raspberry Pi 5 — not by driving a CAD program, but by writing one: a 267-line build123d script whose dimensions were read off Pimoroni\'s official drawing, and which emits every part as STL and STEP, an assembly model with the panel and Pi mocked in place, and section cuts at five heights; the isometric line renders shown on the page are projected from the same geometry. The frame clamps the display through foam instead of screwing into it, hides the panel\'s own bezel behind a 0.8 mm reveal, splits itself into bed-sized quadrants on request, and keeps the microphone outside where it can hear. Shipped with the honesty intact: the design is committed, and zero grams of plastic exist until the calipers agree.',
    shipped: [
      'New page — /cad-as-code/. The full process: an interior-design brief ("make the electronics disappear") plus a vendor\'s dimensional drawing in, eight printable parts out. Why the deliverable is a program rather than a mesh — parameters at the top like a config block, geometry as boolean subtraction, STL and STEP as build artifacts regenerated in seconds when a number changes.',
      'The six mechanical decisions that make it a frame rather than a box: six ø8 foam-tipped clamp posts so nothing fastens into the $299.99 panel (±1.5 mm of tolerance absorbed by the material), the 0.8 mm reveal that hides the panel\'s own black border behind the lip, a parametric half-lap quadrant split so a 312 mm frame prints on a 220 mm bed, face-down printing so the textured plate becomes the museum finish with zero supports, a lay-in cable tunnel + zip-tie saddles + chimney vents + keyholes in both orientations, and the refusal that matters: the microphone capsule stays outside the frame, because a closed box would muffle the station\'s hearing.',
      'The self-verification harness, which is the operator lesson: the final 60 lines of the script are QA, not design. Volume / bounding-box / validity report per part, section SVGs at five heights (a wall too thin shows up as a wrong outline in seconds), isometric line renders for eyeball QA, and an assembly STEP with mock panel and Pi so a human can check fit in one file. The renders on the page are that evidence, unretouched.',
      'The honesty section, kept load-bearing: nothing is printed yet — the commit itself says the panel-thickness and interior-depth parameters await calipers. Dimensions were read off a drawing by a vision model, which is a trust chain, not a caliper — mitigated structurally, because a mis-read number is a sixty-second regeneration. And mouse CAD is not the villain: the repo\'s earlier bird-mic enclosure was hand-drawn in Fusion 360 and works fine; the difference is what the artifact invites.',
    ],
    receipts: [
      { label: 'Vendor drawing → printable parts', value: '1 session · 8 parts + assembly' },
      { label: 'The generator', value: '267 lines of build123d' },
      { label: 'The commit', value: '25 files · 77,177 insertions — STEP is text' },
      { label: 'Screws into the display', value: '0 — six foam-tipped clamp posts' },
      { label: 'Printed so far', value: '0 g — calipers before plastic' },
    ],
  },
  {
    edition: 'Edition 11.0',
    date: '2026-07-30',
    tagline: 'The foundations edition. Every other page here tells you how to operate the tools; this one explains what is happening inside them, using the domain people find most magical. Sound is already numbers — 44,100 of them a second — and the whole breakthrough was compressing that into a few hundred learned symbols a second, short enough for a machine built to finish sentences to finish a song instead. Then the interesting part: the same three-step recipe went and conquered proteins, robot motion and the weather, which is the actual event of the last few years. Shipped with an interactive lab that runs the same pipeline across six alphabets, and with the parts most retellings get wrong kept in — including five claims from my own first draft that failed verification.',
    shipped: [
      'New lesson page — /music-is-math/. The mechanism first: why nobody predicts raw waveform samples (three minutes is ~7.9M numbers), what a neural codec does, and the four numbers that make it concrete — MusicGen at 50 frames/sec with 4 codebooks of 2,048 entries (200 tokens a second, 1,500 prediction steps for 30 seconds of music), MusicLM\'s quoted "one second of audio is represented by 600 tokens", and Descript\'s ~90× compression at 8 kbps. Every figure read off the primary paper.',
      'New interactive widget — TokenizerLab. One four-stage pipeline, six switchable alphabets (music, images, proteins, DNA, robot motion, weather), each with the dialect it actually uses and a card naming where the analogy leaks. Respects prefers-reduced-motion.',
      'The Suno section states a verified absence. Suno has published no paper, model card, or architecture post through v5.5 — so the page cites what IS on the record (the Bark lineage, the CEO\'s 2024 description of next-token prediction over audio tokens, his "tokens per second" constraint) and explicitly refuses to print the 48 kHz specs that circulate without first-party support. Plus the part that actually matters commercially: Suno\'s August 2024 court admission that it trained on "essentially all music files of reasonable quality that are accessible on the open Internet," and the fact that the Warner settlement licenses future models, not the one serving you today.',
      'The universality argument, with the corrections kept in. esmGFP is 58% identical to tagRFP — a RED protein — not "58% similar to anything known"; the 500-million-year figure is a line fit through six anthozoan GFPs, not a measurement; and it took ~184 wells, not one shot. ESM3 is a masked any-order model, not a GPT. π0 abandoned discrete action tokens for flow matching. GenCast\'s verified 97.2% of 1,320 targets in 8 minutes on one TPU v5 — superseded in Google production by WeatherNext 2, which is not a diffusion model at all.',
      'A "where the thesis leaks" section that argues against the page. "One architecture, one objective" no longer holds: 2026 flagship open-weight models interleave linear attention with real attention at about 3:1, and DeepSeek R1-Zero gained 55 points on AIME through RL alone. Images are the weakest link, not the strongest (patches are how models READ, most generators denoise). AlphaGo won by search, not autocomplete. And the taxi-route transformer that found the shortest path 97% of the time while implying a map with physically impossible streets — fluency is not a working model of the thing.',
      'The operator move: three questions (what is the alphabet, how much of it do we have written down, is the next piece predictable) applied to your own repetitive output — plus the Deezer receipt showing where the constraint goes next. Over half of daily uploads there are now fully AI-generated, ~90,000 tracks a day, while AI music is 1–3% of streams. Generation went to zero; selection did not.',
    ],
    receipts: [
      { label: 'Compression, stated as arithmetic', value: '44,100 samples/sec → a few hundred tokens/sec' },
      { label: 'Verified against primary sources', value: '6 research lanes, adversarial re-check on every numeric claim' },
      { label: 'Claims from my own draft that failed', value: '5 — corrected on the page, not quietly dropped' },
      { label: 'Robot data vs text data', value: '10,000 hours (π0) vs 15.6T tokens (Llama 3)' },
      { label: 'Supply vs demand', value: '>50% of Deezer daily uploads AI-generated · 1–3% of streams' },
    ],
  },
  {
    edition: 'Edition 10.9',
    date: '2026-07-27',
    tagline: 'The refresh edition. Two Anthropic models shipped since the last capture — Sonnet 5 on June 30, Opus 5 on July 24 — and one of them broke the rule this site\'s tier list was built on: for as long as these leaderboards have existed, the most capable model was also the priciest. Not any more. Opus 5 took the top of the independent index at LOWER cost per task than the model below it. Every board on Ch 24 is re-captured, the vendor cards now show the public leaderboard beside the launch claim, and there is a new two-page model file on the model itself — with the part most coverage skipped: the launch table runs at max effort, the API default is high, and on debugging the expensive setting scores lower.',
    shipped: [
      'New model file — /opus-5/. Claude Opus 5 shipped 2026-07-24 at $5/$25 per Mtok (unchanged from Opus 4.8, half of Fable 5), 1M context, May 2026 cutoff, default on Claude Max. Specs, exact pricing including the no-long-context-surcharge fact, the full five-position effort ladder priced by Artificial Analysis, and the hierarchy question answered honestly: three independent aggregates disagree about whether Opus 5 or Fable 5 is ahead, and every gap sits inside the evaluators\' own confidence intervals.',
      'New use-cases page — /opus-5/use-cases/. Seven jobs ranked by strength of evidence with the effort setting for each, and eleven documented cases where Opus 5 is the wrong call. The headline finding: on AA-Briefcase, Opus 5 at the DEFAULT effort scores higher than Fable 5 at max for 47% of the cost. The counter-intuitive one: more effort is not monotonically better — on agentic coding the score peaks at medium and declines above high, corroborated by Cognition\'s measurements, Anthropic\'s own docs, and practitioner reports.',
      'Ch 24 fully re-captured. All eleven Arena boards refreshed — and they no longer share a date, so each now carries its own publish stamp (the spread is 34 days). LMArena is now Arena; its HuggingFace feed was retired, so the widget\'s dead live-fetch path was removed rather than left to fail quietly into a fallback. Artificial Analysis re-captured at 17 models — still Intelligence Index v4.1, so the methodology block stands verbatim and only the capture date moves.',
      'The lab-claims cards now show two columns where it matters: the vendor\'s own number beside the public independent board\'s. On FrontierBench that reads 43.3 from Anthropic against 43.5 on the public board — agreement on Opus 5, and a sharp disagreement about its rival, since Anthropic re-ran GPT-5.6 Sol itself at 37.5 while the public board scores it 34.4. Three cards are vendor claims, one (ARC-AGI-3, run by ARC Prize) is independent and labelled as such — the chapter\'s thesis rendered as a column instead of asserted as a sentence.',
      'Arena\'s Agent board added as its own panel rather than a tab, because it does not use Elo — its metric is a Net Improvement Score percentage, and coercing it into the Elo column would be the exact category error Ch 24 exists to argue against. Opus 5 is not on it.',
      'A stat-drift bug fixed in the independent panel: its callout hardcoded the assumption that the smartest model is also the priciest. True in June, false the moment Opus 5 took #1 at $2.03 against Fable 5\'s $2.75. The relationship is now derived from the data rather than asserted over it.',
    ],
    receipts: [
      { label: 'Opus 5 — price vs Fable 5', value: '$5/$25 vs $10/$50 per Mtok' },
      { label: 'Effort ladder span (AA)', value: '6.9× cost, low → max, for ~10 index points' },
      { label: 'The hierarchy', value: '3 independent aggregates, 2 different winners, all gaps inside the error bars' },
      { label: 'Boards re-captured', value: '11 Arena + Agent + AA (17 models)' },
      { label: 'Numbers researched / refuted', value: '40 flagged do-not-publish, incl. 3 that failed verification outright' },
    ],
  },
  {
    edition: 'Edition 10.8',
    date: '2026-06-23',
    tagline: 'The SEO reading. Most "agentic SEO" wins are self-reported traffic graphs that crater in six months. This chapter pulls the real receipts from two products built by AI agents end to end: Folderly EmailGen — a brand-new subdomain that hit #1 for "business email generator," 467K impressions, third-party traffic value climbing ~$0 → ~$320/mo — and LinguaLive, the cautionary tale whose 153K-impression graph looks like a win until you see ~94% of the clicks are people already typing the brand name. The method is triangulation: GSC for footprint, Ahrefs for the independently-checkable commercial keywords, conversions for truth. Do not trust a graph you cannot cross-check.',
    shipped: [
      'New Chapter 48 — "The Traffic Graph That Lies" (Part V). The anti-vanity case for agentic SEO: agents are the labor, a per-page differentiated dataset is the moat, and Google\'s scaled-content-abuse policy is production-method-neutral — "an agent wrote it" earns zero safe-harbor.',
      'Two AI-built products as a natural experiment, with verified numbers. EmailGen (generate.folderly.com): 3,330 clicks / 467K impressions over 12 months, #1 for "business email generator" (KD 36) confirmed by Ahrefs, traffic value stepped from ~$0 to ~$290–390/mo. The honest caveats kept in: 0.7% CTR, average position 13, and one query printing 14,350 impressions for 81 clicks.',
      'LinguaLive (lingualive.ai) as the cautionary tale: a 153K-impression / 1.33K-click graph where ~94% of top-query clicks are branded, the non-branded long-tail earns ~3 clicks each, and independent traffic value is ~$12/mo. The first-party-vs-third-party divergence (GSC ~1,000 queries vs Ahrefs 21 keywords) is the whole lesson: triangulate, or you are the next 24k-clicks screenshot.',
    ],
    receipts: [
      { label: 'EmailGen — GSC, 12 mo', value: '3.3K clicks / 467K impr' },
      { label: 'EmailGen — Ahrefs commercial', value: '#1 "business email generator"' },
      { label: 'LinguaLive — branded clicks', value: '~94% of top queries' },
    ],
  },
  {
    edition: 'Edition 10.7',
    date: '2026-06-18',
    tagline: 'The builder\'s eval, one altitude above Chapter 25. Chapter 25 was a three-line smoke detector for a skill\'s artifact; Chapter 47 is for when the model\'s output is the product itself. The Anthropic API course ships, as working code, the two tools most builders never build — a way to SCORE output and a way to RETRIEVE the right context. Both ported to TypeScript over a weekend: a PromptEvaluator (synthetic dataset → cheap code-grade + LLM-judge → honest scorecard) and a hybrid BM25+vector retriever. The point isn\'t the 400 lines; it\'s that you can stop charging for AI output you can\'t score.',
    shipped: [
      'New Chapter 47 — "The Measurement Layer" (Part V). Bridges from Chapter 25\'s operator eval to a builder\'s graded test set: generate a synthetic dataset, grade cheap-first (deterministic checks before any judge token), judge with reasoning-before-score, and print a scorecard that shows its failing cases — never a vanity average.',
      'The RAG half: why lexical (BM25) and semantic (vector) search fail in opposite directions — BM25 nails exact identifiers an embedding blurs; vectors catch paraphrase keywords miss — fused by rank (reciprocal rank fusion), not by mismatched raw scores.',
      'Receipts are the real thing: ~400 lines of glue extracted from Anthropic\'s course into two tested TypeScript libraries, 29 tests green, the deterministic gate proven to score a known-good reply 10 and a deliberately-toxic one 0 with no model in the loop. No live pass-rate is claimed — the harness is built and staged; the first product wiring is next.',
    ],
    receipts: [
      { label: 'Course → TS, tested', value: '29 tests green' },
      { label: 'Eval + RAG glue', value: '~400 lines' },
      { label: 'Deterministic gate (good / bad)', value: '10 / 0' },
    ],
  },
  {
    edition: 'Edition 10.6',
    date: '2026-06-16',
    tagline: 'The showcase. Chapter 46 argued that taste is the last mile; /good-taste makes it visceral — a side-by-side of generic-AI slop (purple glow, floating blobs, a fake dashboard) next to the same brief art-directed with a public skill. The skill is Leon Lin\'s open-source taste-skill (github.com/Leonxlnx/taste-skill, 45k+ stars), not mine; this page is what stealing a skill well, with credit, looks like.',
    shipped: [
      'New page /good-taste — a before/after gallery (slop vs. taste, same prompt), the skill catalog, a 60-second npx install, and the receipts (flicked.email\'s three designs, the Reach moon-base study, this book\'s own design system). The "before" is an honest generated example of un-directed AI slop — every tell on the skill\'s own ban-list.',
      'Honest attribution throughout: taste-skill is Leon Lin\'s MIT-licensed project (Leonxlnx/taste-skill), and it runs across Codex, Cursor, and Claude. The page credits the author, links upstream, and frames the whole thing as the Ch 39 "steal it well, with credit" move — not a Belkins product.',
    ],
    receipts: [
      { label: 'The skill (credited, not claimed)', value: 'Leonxlnx/taste-skill · 45k★' },
      { label: 'Before / after, same prompt', value: 'slop → directed' },
      { label: 'Install', value: 'npx skills add' },
    ],
  },
  {
    edition: 'Edition 10.5',
    date: '2026-06-16',
    tagline: 'The design reading. Forty-five chapters taught you to build with AI; none taught you to make it look like something. Chapter 46 fills the gap with the book\'s own receipts — a contrast failure that sat in our light-theme tokens for weeks until the arithmetic caught what every eye had passed, flicked.email\'s three landing pages in three different typefaces, and a moon-base image set for Reach art-directed with a public taste skill. Generation went to zero; selection didn\'t.',
    shipped: [
      'New Chapter 46 — "Designing with AI" (Part V). The thesis: the model generates, the human selects, the system remembers the selection. It opens on the WCAG light-accent miss — flame at ~2.7:1 and terminal at ~1.7:1 doing text duty on light, a latent token omission the arithmetic caught after every eye had passed it — then runs through swarm-before-v1 and the design-system-as-a-ruler, and proves the thesis on a second product.',
      'The flicked.email case study, pixel-verified: one product, three live landing pages — chaos, hype, calm — in three different heading typefaces (Bricolage display / Inter sans / Fraunces serif), with the brand mint #35E8B8 as the only constant. Intent is the input; the model is the executor; which intent is right is a taste call it can\'t make for you.',
      'An honest "which model for which design job" matrix — first-person is Claude and Claude Code; every other tool (GPT, v0, Lovable, Midjourney, Figma AI) is labeled researched, not a war story I didn\'t earn.',
      'A new section on designing the images, not just the layout — AI image generation as art direction: one image per section, kill the default hero, pick one of each variable, run the anti-slop ban-list. The worked example is a moon-base concept set for Reach by Folderly — a pre-build art-direction study shown via real mockups, made with an image model (ChatGPT, not Claude). The skill behind it is public, by Leon Lin: github.com/Leonxlnx/taste-skill (45k+ stars) — credited, not claimed.',
    ],
    receipts: [
      { label: 'The contrast miss the eye passed, the math caught', value: '2.7:1 / 1.7:1 → ≥4.5:1' },
      { label: 'flicked.email — one product, three typefaces', value: 'display / sans / serif' },
      { label: 'Reach moon-base set — real mockups', value: 'one world, many layouts' },
      { label: 'Chapters', value: '45 → 46' },
    ],
  },
  {
    edition: 'Edition 10.4',
    date: '2026-06-16',
    tagline: 'The fourth reading — the tier list gains an independent referee. Between the crowd\'s LMArena votes and the vendors\' launch decks, Artificial Analysis runs its own agentic harness and prices every run, so you can finally sort the leaderboard by what a task actually costs, not just by who scores highest.',
    shipped: [
      'New "What an independent referee measures" panel on /tier-list — Artificial Analysis\'s agentic Intelligence Index v4.1 (Terminal-Bench 2.1, 𝜏³-Banking, GDPval-AA v2; IFBench retired) alongside its new per-task economics. Three sort pills — Intelligence, cost-per-task, speed — re-rank the same ten models live, so the intelligence-vs-cost inversion is something you feel: the #1 model on the Index (Claude Fable 5, 59.9) is the most expensive per task at $3.25, ~58× DeepSeek V4 Pro\'s $0.056. Hand-captured fair-use snapshot from AA\'s public board (2026-06-16), attributed with a link-out, and a staleness guard that ages the data honestly.',
      'The tier list is now four readings of the same models, not three — the crowd (LMArena), the independent referee (Artificial Analysis), the labs (launch-deck claims), and the operator (Vlad\'s drag-and-drop). Different question, different answer, now with economics as the bridge to the operator\'s question. AA is independent, not infallible — its Index is a weighted composite, framed as a third reading that triangulates, never a new oracle.',
      'AEO/discovery wiring — a visible v4.1 methodology breakdown (the 34% agentic weighting, extractable), FAQPage structured data for "cheapest agentic model" / "what is cost per task" / "is Artificial Analysis independent", Cmd-K keywords, and a rewritten llms.txt entry so the four-panel framing reaches the answer engines.',
    ],
    receipts: [
      { label: 'Most capable model · AA Index v4.1', value: 'Claude Fable 5 · 59.9' },
      { label: 'Its cost per task (the priciest on the board)', value: '$3.25' },
      { label: 'Cheapest per task on the board', value: 'DeepSeek V4 Pro · $0.056' },
      { label: 'Independent agentic models priced side by side', value: '10' },
    ],
  },
  {
    edition: 'Edition 10.3',
    date: '2026-06-11',
    tagline: 'The economics week — the research timeline gets the grid that turns "this plan can\'t be profitable on me" into numbers, and the tier list catches up to the Fable 5 era with a fresh LMArena snapshot and a new lab-claims panel.',
    shipped: [
      'New research note (top of the timeline) — "The subscription subsidy, quantified." SemiAnalysis\'s Tokenomics model: a $20 claude-pro can draw ~$400/mo of API-equivalent compute, a $200 claude-max-20x ~$8,000, a $200 chatgpt-pro-20x ~$14,000. Break-even utilization per tier, the −900%/−1,650% full-utilization gross margins, and the three honest discounts to apply before quoting any of it. The two source tables are embedded as receipts and redrawn as native elements — an option-value table and a break-even bar strip where the green sliver is the business model. The operator read: every limit you\'ve ever hit is the mechanism that drags the average back into the green columns.',
      'Tier-list benchmark refresh — LMArena snapshot 2026-05-18 → 2026-06-11, pulled from the same HF dataset the widget fetches live. Fable 5 debuts at #1 WebDev (1665, ~100 Elo clear of #2) and #1 Vision; Opus 4.8 enters the boards. Freshness strings are now absolute board-publish dates; the two boards stuck at 05-18 say so instead of pretending.',
      'New "What the labs claim" panel on the tier list — the missing third axis next to crowd votes and operator usefulness: SWE-Bench Pro, FrontierCode Diamond, OSWorld, and Terminal-Bench launch numbers, every figure corpus-traceable to a dated research note and framed with the Berkeley-RDI discount. Mythos excluded — tier the models you can buy.',
      'Homepage repair + banner history — the stack tile was rendering broken (an anchor nested inside the card anchor; browsers force-close the outer one and eject the description into a floating fragment — invalid HTML, now a span). The announcement bar grew a history toggle: click the clock to see the last few editions and when they shipped, without leaving the page.',
      'Research-notes page rebuilt for scannability — twelve fully-expanded notes were a wall. The timeline is now a chronological index (it wasn\'t even date-sorted before) chunked by month, each row carrying date, a category chip, the title, an ink-italic tagline, and a receipts/implications/reading-time meta line. Notes unfold on click (newest open by default), findings read as paragraphs instead of 2,000-character blocks, receipts render as an aligned spec sheet, implications are numbered. Expand-all for Ctrl-F and print, NEW pills since your last visit, RSS deep-links land open and clear of the nav. And the light theme finally re-tints the accents — flame and terminal were failing WCAG contrast on light backgrounds everywhere they did text duty.',
    ],
    receipts: [
      { label: 'API-equivalent compute a $200 max-20x plan can draw', value: '~$8,000/mo' },
      { label: 'Break-even utilization, claude-max-20x', value: '10% of cap' },
      { label: 'Fable 5 LMArena WebDev debut', value: '#1 · 1665 Elo' },
      { label: 'Nested-anchor bugs found by the site-wide scan', value: '1 of 1 fixed' },
    ],
  },
  {
    edition: 'Edition 10.2',
    date: '2026-06-10',
    tagline: 'The reference layer — five search-facing pages distilled from the corpus, each built on receipts the official docs can\'t print: the real bills, the configs that fired, the agents that broke. Plus the machine plumbing: every deploy now announces itself to the indexes ChatGPT and Claude actually read from.',
    shipped: [
      'Five new reference pages, every claim traced to a chapter or a first-party source verified on ship day: /claude-code-pricing (every plan + API rate, verified 2026-06-10, beside the real monthly bill and the $1,108→$4,312 cache-void week), /claude-code-vs-codex (ran both in anger — verdict per job), /claude-code-mcp (the setup guide grounded in a real server roster), /claude-code-hooks (ten configs with verdicts, including the exit-1-doesn\'t-block correction the chapter version missed), /ai-agent-examples (12 agents that actually ran, each with a cost and a failure on record).',
      'Title re-aims on three existing pages — the sovereign stack now leads with "Local LLM & Self-Hosted Models", the cheat sheet with "Claude Code Commands", swarms with "AI Agent Orchestration". Title slot only; every human-readable word unchanged.',
      'IndexNow on deploy — the site announces all of its URLs to Bing/Brave/Yandex on every push. Bing\'s index is what ChatGPT search retrieves from; Brave\'s is Claude\'s. The site was invisible to both pipelines until this week.',
    ],
    receipts: [
      { label: 'New reference pages', value: '5' },
      { label: 'Real agent examples, each with a cost and a failure', value: '12' },
      { label: 'Hook configs judged', value: '10' },
      { label: 'URLs announced per deploy via IndexNow', value: '~95' },
    ],
  },
  {
    edition: 'Edition 10.1',
    date: '2026-06-09',
    tagline: 'The Self-Audit — the multi-agent audit pointed at the layer nobody reviews: the agent\'s own configuration. Run the same evening Fable 5 landed, on the thesis that a capability jump is a standing audit trigger for the scaffolding under it.',
    shipped: [
      'New method page: /self-audit — five parallel auditors (skill library, per-session context budget, memory system, hooks + permissions, automation layer) followed by an adversarial red-team that re-verifies every high/medium finding empirically and lists what all five auditors missed. The session\'s real numbers kept as receipts: 41 findings, 29 confirmed, 4 weakened, 2 refuted, 8 missed-by-all.',
      'The two refutations argued in full — the engines-behind-the-keepers catch (two individually-reasonable auditor recommendations whose combination would have deleted the engines of the skills marked "keep") and the wrong-denominator catch (context-budget urgency computed against a 200k window on a 1M-context model, overstating the crisis five-fold). The lesson the page is built around: a single-pass audit produces confident, well-evidenced, wrong advice.',
      'The operating rules distilled: telemetry before deletion (a one-line usage-logging hook turns "I think I use this" into "zero fires in seven weeks"), archive over delete (reversible removal converts each kill from a debate into an experiment), memory is part of the audit surface (an auditor cited a stale memory note as evidence for a claim a later commit had already fixed), and the OS-scheduler spine for everything that must outlive the session — including the launchd-vs-Desktop privacy gotcha that kept a job silently dead at exit 126 for weeks.',
      'Full wiring — homepage tile, Cmd-K page + 8 section entries, a cross-link from Chapter 39\'s "73% problem" (the same rot, public vs. private), a Self-Audit glossary term, and the llms.txt entry.',
    ],
    receipts: [
      { label: 'Findings', value: '41 — 29 confirmed · 4 weakened · 2 refuted · 8 missed-by-all' },
      { label: 'Skills', value: '81 → 66, on telemetry, archived not deleted' },
      { label: 'Permission grants', value: '162 → 49, incl. a live token and a keychain read' },
      { label: 'Memory index', value: '26.6 KB (silently truncating) → 18.2 KB' },
    ],
  },
  {
    edition: 'Edition 10.0',
    date: '2026-06-09',
    tagline: 'Fable 5 / Mythos 5 — the withheld model shipped, and the Playbook files it the day it lands: a research note that corrects the May 6 call, a ten-page model file (incl. the system-card episodes), and the three evergreen pages the keyword map has been waiting for.',
    shipped: [
      'New research note (top of the timeline) — "Fable 5 / Mythos 5 — the withheld model shipped, split in two." The May 6 note read the Mythos disclosure as a capability ceiling Anthropic would not productize; the correction is the mechanism nobody predicted: one model, two names (Latin fabula / Greek mythos), the raw twin gated behind Project Glasswing, the safeguarded twin sold to everyone at $10/$50 per Mtok with classifier fallback to Opus 4.8.',
      'New model file: /fable-5 — a hub plus nine spokes, each owning one question. vs-mythos-5 (one model, two names, three safeguards), benchmarks (the full 13-benchmark launch table with the Berkeley-RDI discount applied), vs-opus-4-8 (upgrade or wait), vs-gpt-5-5 (cross-vendor, incl. Gemini 3.1 Pro), pricing (sticker vs cost-per-task), use-cases (Stripe\'s 50M-line day, drug design, genomics — vendor-curated and labeled as such), claude-code (the banner, the June 22 clock, the routing), api (claude-fable-5, the advisor seat, the one new 400), and system-card (the ten strange pre-release-testing episodes, each verbatim-sourced from the 319-page Mythos 5 / Fable 5 system card and mapped to the operator guardrail it demonstrates).',
      'The two launch demos embedded — Fable 5 beating Pokémon FireRed on raw screenshots (vision only, no maps, no navigation aids — previous Claude models could not finish it even with helper harnesses) and the solar-system/eclipse simulation.',
      'The developer-facing fine print folded in: blocked API requests return an unbilled error with fallback-to-Opus-4.8 opt-in at Opus pricing (built into the apps and Managed Agents); Fable 5 as an advisor model — cheap workers call it mid-task to check plans, the book\'s conductor-and-judge split as an API primitive; the 30-day misuse-only retention and the Console terms gate.',
      'Three evergreen pages from the SEO/AEO keyword map, every claim chapter-sourced: /claude-code-best-practices (the practices that survived production, distilled from 45 chapters), /claude-code-vs-cursor (the comparison the answer engines currently source from Reddit), /what-is-agentic-coding (the operator\'s definition, with the 90k-line worked example).',
      'Full wiring — homepage model-file tile, mobile-nav entries, 12 Cmd-K entries, four glossary terms (Fable 5, Mythos 5, Mythos-class, and a disambiguated Mythos), three new inbox questions with FAQPage schema, llms.txt entries for every new page, and this changelog.',
    ],
    receipts: [
      { label: 'New pages', value: '12 — /fable-5 hub + 8 spokes + 3 evergreen' },
      { label: 'The model', value: 'claude-fable-5 · $10/$50 per Mtok · 1M context' },
      { label: 'The correction', value: 'May 6 "Mythos isn\'t coming" → it came, split in two' },
      { label: 'The clock', value: 'included in plan limits Jun 9–22, then usage credits' },
    ],
  },
  {
    edition: 'Edition 9.9',
    date: '2026-06-08',
    tagline: 'Forty-five chapters. The App Store Without Swift — Claude Code one-shot a native iOS app for LinguaLive, and shipping it to the App Store meant walking through the gates the operator, not the agent, has to own. The proof is a RevenueCat renewal, read honestly.',
    shipped: [
      'New Chapter 45 — "The App Store Without Swift" (Part V, The Building Site; Building Products section). The apex of the build-a-product arc: Claude Code one-shot every line of native SwiftUI for LinguaLive and still could not ship it. The App Store is just another deploy target — with the strictest gates in the book, and the operator owns every one: a Mac + Xcode, the $99/yr Developer Program, the signing maze, account deletion (Guideline 5.1.1(v)), the App Privacy label, and a working demo login for the reviewer.',
      'The reframe, Ch 43-style: the lesson is not "you can build iOS without Swift" — the code is the easy part now. It is that shipping native means owning the platform-and-policy surface the agent is structurally locked out of. Ties straight to Ch 41 (proof is a live artifact, not a file) and Ch 43 (verify with real behavior is the whole game).',
      'The proof is recurring revenue, read honestly. Real App Store numbers — LinguaLive Monthly Pro $7.99 and Pro Annual $79.99, an INITIAL_PURCHASE that became a RENEWAL — recreated as an on-brand dashboard that teaches the reader to read it without inflating it: a RENEWAL is recurring revenue not a new customer, $RCAnonymousID is an anonymous buyer not a redaction, the dollars are gross estimates not a bank deposit, and the row proves recurring revenue and a stacking renewal, NOT total scale. Apple\'s cut is stated correctly (never a flat 30% — 30% year one, 15% after, or 15% flat under the Small Business Program).',
      'Three house-style inline SVG diagrams (palette-correct, librsvg render-verified, mobile-legible): the receipt read honestly, the agent-owns-the-code / operator-owns-the-gates map, and the web→native arc tracing one dollar from a real-phone tap through StoreKit and Apple to the dashboard row.',
      'Built by the deep multi-agent workflow chain — a four-researcher swarm verified the App-Store-without-Swift reality against Apple\'s own docs (signing, IAP / Guideline 3.1.1, account deletion, the tiered commission, RevenueCat) plus a completeness critic, then a three-perspective design swarm (reframe / receipts / journey) reconciled by a synthesis judge. Every platform fact is primary-sourced; every lived LinguaLive number is sourced or left to the author, never invented.',
      'Wiring — chapters.ts (CHAPTERS + Part V + the Building section), Cmd-K synonyms, and this changelog. Chapter-count stat swept 44 → 45 across the user-facing pages and the lint-invisible OG/ad cards (og-default, og-launch, the −90k ad).',
    ],
    receipts: [
      { label: 'New chapter', value: 'Ch 45 · 45-app-store-no-swift · Part V — The Building Site' },
      { label: 'Subject', value: 'LinguaLive — native iOS, App Store, real recurring revenue' },
      { label: 'Proof', value: 'RevenueCat renewal · $7.99/mo + $79.99/yr · read honestly' },
      { label: 'Built by', value: 'research swarm (Apple-sourced) → design swarm → synthesis' },
    ],
  },
  {
    edition: 'Edition 9.8',
    date: '2026-06-05',
    tagline: 'Learn — the on-ramp before the book. A new /learn page routes total beginners through the official free courses, in order, then hands them to the Playbook.',
    shipped: [
      'New standalone page /learn — the entry point for anyone new to AI, Claude, Claude Code, or Cowork. A staged learning ladder (concepts → official courses → orient + set up → read and build), a five-word concepts primer that links the glossary instead of redefining it, and a no-code vs builder split that meets back up at the end.',
      'The full official course catalog, verified live and ordered — not dumped. Anthropic Academy first (Claude 101, Claude Code 101, Cowork, Agent Skills, Subagents, the Claude API, MCP, docs + cookbooks), then OpenAI and Google official academies, then hand-picked independents (DeepLearning.AI, Hugging Face, Microsoft). 28 resources; only the 3-card foundation shows by default, the rest behind drawers so it never becomes a wall.',
      'Four house-style inline SVG diagrams (palette-correct, viewBox-only, mobile-legible): the learning ladder, chatbot-vs-OS, the agent loop, and the ecosystem map. A "what you will build" section points at real receipts (the HTML-ization weekend, the one-day product, the twelve-file workflow refactor) plus Anthropic\'s own customer numbers.',
      'Designed and built by a deep multi-agent workflow — research across every vendor learning ecosystem (links HTTP-verified), curriculum + IA + diagram design, Vlad-voice copy, then an adversarial red-team that cut a mis-sourced stat, two stale "free" cards, and a 31-card wall before any of it shipped.',
      'Wiring — new Learn tab in the nav, a flagship homepage tile + hero CTA, Cmd-K entry + section deep-links + popular default, and this changelog. Chapter count unchanged.',
      'Fact-checked post-ship — all 28 course/resource links re-verified live; corrected the Satispay descriptor (the headcount was not on the cited source), reframed the one-day build to the honest "shipped in a Saturday" per Ch 19, added paid-plan/beta caveats to the Cowork + two DeepLearning.AI cards, and added a "stuck? paste the error back into Claude" line.',
    ],
    receipts: [
      { label: 'New page', value: '/learn · onboarding on-ramp · 7 sections, 4 diagrams' },
      { label: 'Courses', value: '28 verified-live (Anthropic · OpenAI · Google · independents)' },
      { label: 'Built by', value: 'deep multi-agent workflow + adversarial red-team' },
      { label: 'Wiring surfaces', value: 'Nav · homepage tile + hero CTA · Cmd-K · changelog' },
    ],
  },
  {
    edition: 'Edition 9.7',
    date: '2026-06-04',
    tagline: 'Forty-four chapters. Dreaming — the autonomous loop pointed inward: a local, propose-only twin of Anthropic\'s memory feature that surfaces candidate lessons from your own sessions and verifies every quote against the raw transcript, but never writes to memory itself.',
    shipped: [
      'New Chapter 44 — "Dreaming — Memory That Curates Itself" (Part II, Working Memory; also in the General + Claude sections). The curation layer Ch 37 leaves open: it teaches the four memory layers but never how memory stays deduped, true, and under its bloat ceiling across hundreds of sessions. Dreaming is that loop — and the one autonomous loop in the book that is structurally forbidden to write.',
      'New standalone page /dreaming — the operator runbook: the five-stage pipeline (select → digest → extract → verify → review, and only extract is the model), the five refusals, the receipts, the data-locality "exception to Chapter 7" (why you never cloud-cron a local-disk corpus), and when not to run it.',
      'The thesis — every autonomous loop in the Playbook points outward (the swarm reads the codebase, cron reads the calendar, run-until-done reads the task); Dreaming is the first pointed at the agent\'s own memory, so it gets less rope, not more. Propose-only is the ceiling, not just the default: the most the pipeline can do is write one review file a human acts on via /learn.',
      'Receipts, stated honestly — two real runs: single-project (3 sessions → 3 candidates → 3 verified) and cross-project (6 sessions across 3 projects → 15 candidates → 15 verified, 0 dropped, 14 net-new, 1 the tool flagged as a duplicate). The failure kept in: it caught the dup it could see (against the portfolio index) and honestly missed two that lived one level down in a project\'s own memory — the design\'s open question #10, confirmed in the wild on run one.',
      'The method shown — Chapter 44 and the page were themselves planned by an 8-agent design swarm (five perspective architects → reconciler + red-team → synthesis); the red-team caught and corrected an over-stated receipt against disk before it could ship. Two real /workflows screenshots wired in.',
      'Full 6-surface wiring — chapter + page, Cmd-K entry + section deep-links + synonyms, glossary terms (Dreaming, Agent memory, Memory curation, Propose-only), homepage flagship "Memory" tile, llms.txt + entity graph (author knowsAbout), and this changelog. Chapter-count stat swept 43 → 44 across the user-facing pages.',
    ],
    receipts: [
      { label: 'New chapter', value: 'Ch 44 · 44-dreaming · Part II — Working Memory' },
      { label: 'New page', value: '/dreaming · pipeline + 5 refusals + receipts + runbook' },
      { label: 'Chapter count', value: '43 → 44' },
      { label: 'The run', value: '6 sessions · 15 verified · 0 dropped · 14 net-new · 1 flagged dup' },
      { label: 'Glossary terms', value: 'Dreaming · Agent memory · Memory curation · Propose-only' },
    ],
  },
  {
    edition: 'Edition 9.6',
    date: '2026-05-28',
    tagline: 'Dynamic Workflows — a standalone page on Opus 4.8\'s headline feature: the swarm that runs itself.',
    shipped: [
      'New standalone page /dynamic-workflows — Opus 4.8 ships dynamic workflows: Claude writes a JS script that plans a big task, fans out up to 16 parallel subagents (1,000 per run), runs an adversarial verifier pass, and reports one answer. Part explainer (what it is, agent-teams vs workflows, the generator->validator loop), part operator\'s read, part reference.',
      'The validator loop is the spine — one set of agents builds, another tries to break it, a fixer closes the gap. The /effort dial + ultracode are the on-ramp (ultracode = xhigh + automatic workflow orchestration). With a first-person take and a "when not to run a workflow" section so it reads as judgment, not hype.',
      'Receipts over claims — every number is from Anthropic\'s announcement or the Claude Code docs (16 concurrent / 1,000 per run, research preview, v2.1.154+, the Bun Zig->Rust port: 750k lines in 11 days at 99.8% tests). The /effort slider screenshots + a clip of the dial in motion + a house-style agent-teams-vs-workflows diagram.',
      'Full 6-surface wiring — page, Cmd-K entry + section deep-links, Ch 40 cross-link, glossary terms (Dynamic workflows, Agent teams, /effort, ultracode), homepage flagship tile, and this changelog entry.',
    ],
    receipts: [
      { label: 'New page', value: '/dynamic-workflows · explainer + operator read + reference' },
      { label: 'Glossary terms', value: 'Dynamic workflows · Agent teams · /effort · ultracode' },
      { label: 'Scale documented', value: '16 concurrent · 1,000 agents / run' },
      { label: 'Wiring surfaces', value: '6/6' },
    ],
  },
  {
    edition: 'Edition 9.5',
    date: '2026-05-23',
    tagline: 'Forty-three chapters. The Codex loop from Ch 42 runs for real — a 90,000-line product refactor, proof-checked.',
    shipped: [
      'New Chapter 43 — "Codex as Saviour" (~2,390 words, 13-min read). The full-scale payoff of Ch 42\'s standing loop ("simplify, follow my design system"): pointed at a real shipping product (Folderly Email Generator), a bench of fourteen named explorer agents deleted a net 91,874 lines across 718 files, repositioned the product from seven surfaces to one promise, and HARDENED the risky paths the simplification exposed — all behind real build, CI, browser, and API checks. The thesis: simplification and security are the same phase.',
      'The numbers, reconciled — hero stat is the final shipped release (718 files, +43,092 / −134,966, net −91,874, 243 commits, 106 begin with "Simplify", 27 hardening). The mid-run screenshot counter (585 files / +30,928 / −55,984) is framed explicitly as the diff mid-flight before the branch finished, not a contradiction. Plus the real cost receipt — 46% of one week\'s usage — and the human-steer receipt: the operator told the loop to checkpoint mid-run ("test the build, commit and push if no regressions").',
      'The bench — the literal swarm (Pauli, Planck, Hume, Ramanujan, Averroes, Gibbs, Fermat, Sagan, Hooke, Socrates, Feynman, Beauvoir, Franklin, Mill) mapped onto a conceptual ten-lens decision model with veto power. The insight you steal: the lenses disagree productively — a delete that helps UX can hurt SEO, a security fix can break an integration — so the swarm forces each tradeoff explicit before code lands. Cross-links Ch 6 (the swarm).',
      'The paste-able artifact — the eight-phase simplification playbook as a copy-paste block (name the product in one sentence → split the surface into four buckets → preserve before pruning → reduce first-use decisions → move power behind intent → delete by category → harden while simplifying → ship in verified layers).',
      'Harden while simplifying — Phase 7 written as a generalized bug-class checklist an operator runs on ANY product (does a route mutate on GET? are OAuth states signed? are entitlements server-side? do protected APIs return JSON 401 or a confusing redirect? does cron auth fail closed?), not a Folderly incident report. Sanitized for public publication.',
      'Four authored house-style SVG diagrams (the dark/orange book palette crossed with Folderly blue #195EE6 to encode before→after): the bench roster + veto lenses + the Emberling pet from Ch 42, the seven-surfaces→one-promise repositioning, the delete-by-the-numbers stat card, and the four-bucket surface split.',
      'Placed in Part VI (Frontier + Tier) next to Ch 35 and Ch 42, and in the SECTIONS "AI agents" group. Cmd-K entry + synonyms. Three inbound cross-links so Ch 43 is a node, not a dead end: Ch 42 (the pet-joke payoff — "the loop actually ran it"), Ch 35 (the full-scale receipt of the day/night-shift loop), Ch 38 (what the fence looks like at 90,000 lines).',
      'Executed as a swarm — voice-calibrated drafting agent (read Ch 35/42/38/6 first) + parallel SVG authoring + adversarial proof-check. Chapter-count stat swept 42 → 43 across the user-facing pages.',
    ],
    receipts: [
      { label: 'New chapter', value: 'Ch 43 · 43-codex-saviour · Part VI · ~2,390 words' },
      { label: 'Chapter count', value: '42 → 43' },
      { label: 'The delete', value: '718 files · net −91,874 lines · 243 commits' },
      { label: 'Authored diagrams', value: '4 house-style SVGs (book palette × Folderly blue)' },
    ],
  },
  {
    edition: 'Edition 9.4',
    date: '2026-05-21',
    tagline: 'Forty-two chapters. Codex gets the hands-on companion — second opinion, on a loop, proof-checked.',
    shipped: [
      'New Chapter 42 — "Codex on a Loop" (~1,950 words, 11-min read). The hands-on companion to Ch 35\'s strategic day-shift/night-shift framing. The thesis: Codex isn\'t a better Claude Code, it\'s a second prior I run on a loop — pointed at Sentry (errors), PostHog (funnel-drop anomalies), and BetterStack (uptime/log alerts) via MCP + crons, fixing fresh signals in worktree-isolated PRs, and proof-checking the day driver\'s diffs by running the tests CC didn\'t think to run.',
      'The honest framing — explicit "this is NOT Codex beats Claude Code" callout that defers the ranking to /tier-list. Same second-prior logic as the Gemini argument in Ch 35: the value is the delta, never the leaderboard.',
      'The loop, with a fence — the standing `/loop` prompt ("simplify, follow my design system") plus the discipline that makes it safe: an evaluator that says stop (cross-link Ch 38) and a diff ceiling that caps blast radius. A four-file simplification is a fix; a nine-file one is a re-architecture wearing a fix\'s clothes.',
      'Proof-checking as the whole discipline — two levels: Codex proof-checks CC\'s PRs (machine), the human proof-checks the loop (judgment). Best execution = a second opinion plus a proof check, never one agent trusted blind.',
      'Ten minutes to a desktop pet — the fun payoff and the lightest proof the cross-vendor SKILL.md claim holds: handed Codex the `hatch-pet` skill + a one-line cyberpunk brief, it read the contract, generated + self-validated sprite assets in a worktree, and hatched "Emberling" — a half-robot/half-flame desktop pet — in ~10 minutes. 4 real screenshots wired in (Codex conversation, contact sheet, live animation gif, pet-on-desktop).',
      'Placed in Part VI (Frontier + Tier) next to Ch 35, and in the SECTIONS "AI agents" topical group. Cmd-K entry + synonyms (codex loop worktree sentry posthog betterstack proof-check pet emberling hatch-pet second opinion).',
      'Executed as a swarm — voice-calibrated drafting agent + adversarial proof-checking pass. The chapter keeps its own receipt: it says so in the text.',
      'Consistency pass — chapter-count stat swept 41 → 42 across 5 user-facing pages (homepage header + Now banner + launch tile, /journey, /sections, /launch, /github-playbook). Two copy-pasteable artifacts added to Ch 42 (the LinguaLive product-analytics .mcp.json; the worktree + fenced /loop commands). Three inbound cross-links added so Ch 42 is a node, not a dead end: Ch 38 (a real /loop example), Ch 39 (the hatch-pet cross-vendor receipt), Ch 20 (worktree-per-fix in practice). The last screenshot slot filled with a house-style loop-flow diagram.',
    ],
    receipts: [
      { label: 'New chapter', value: 'Ch 42 · 42-codex-on-a-loop · Part VI · ~1,950 words' },
      { label: 'Chapter count', value: '41 → 42' },
      { label: 'Real screenshots added', value: '4 (hatch-pet conversation, contact sheet, Emberling gif, desktop pet)' },
      { label: 'Emberling gif weight', value: '3.8 MB → 2.4 MB (gifsicle -O3 --lossy)' },
    ],
  },
  {
    edition: 'Edition 9.3',
    date: '2026-05-20',
    tagline: 'Every page one click from the homepage. Tile grid grows to 3 rows.',
    shipped: [
      'Homepage tile grid expanded from 8 → 12 tiles (3 rows of 4). Row 3 added: Swarms · GitHub Playbook · Setup showcase (62 skills · 32 agents · 12 plugins) · Research notes (what shifted this week). The pages I shipped this week are now first-class tiles, not secondary-row text links.',
      'Hanging-pages cleanup — secondary text row rewritten to surface the remaining 10 previously-hanging pages: Build vs Buy · For your CFO · CLAUDE.md rules · Cowork setup · Vault starter · Weekend builds · Starter skills · 30-day plan · Sections · About. Every standalone page in the Playbook is now one click from the homepage.',
      'Reachability audit complete — 27 user-facing pages audited (plus /the-bill which is intentionally sitemap-excluded). Zero orphans, zero hanging-from-homepage pages remain.',
    ],
    receipts: [
      { label: 'Homepage tiles', value: '8 → 12 (+4 third-row tiles)' },
      { label: 'Pages reachable from homepage', value: '13 → 27 (every page surfaced)' },
      { label: 'Hanging pages (after audit)', value: '0 (was 9 pre-audit)' },
      { label: 'Orphans', value: '1 — /the-bill, intentional sitemap exclusion' },
    ],
  },
  {
    edition: 'Edition 9.2',
    date: '2026-05-20',
    tagline: 'Forty-one chapters. The HTML-ization thesis gets its own chapter slot.',
    shipped: [
      'New Chapter 41 — "Send the Link, Not the File" (~1,800 words, 9-min read). Chapter-length narrative companion to /html-first. The story version of the HTML-ization thesis: every report, pitch, audit, deck, model in the portfolio ships as a live interactive link in a private repo, not a PDF or slide attachment. Same recipe across the portfolio; the chapter tells the story, /html-first is the deep reference with the embedded case studies, the recipe, the gallery, and the 12 public examples in the wild.',
      'Ch 41 placed in Part V (Building Site) — sits next to Ch 19 (Saturday builds), Ch 31 (six stages), Ch 38 (run until done). Also in SECTIONS "building" topical group.',
      'Cmd-K — Ch 41 chapter entry + synonyms (html htmlization living-link artifact deploy private repo afc folderly qbr board update)',
      'Hanging-pages audit + homepage secondary text row expanded — surfaced /swarms, /github-playbook, /showcase, /resources, /research-notes alongside /about. Five previously-hanging pages now one click from the homepage.',
      'Stale "39 chapters" → "41 chapters" across 11 user-facing sites: homepage hero stat ("39 chapters"), homepage section header ("Thirty-Nine Chapters" → "Forty-One Chapters"), Now banner copy, launch-tile description, /journey description meta + body, /sections description meta + body, /launch description meta + body, /github-playbook example card. Historical changelog entries kept original count (accurate at the time).',
    ],
    receipts: [
      { label: 'New chapter', value: 'Ch 41 · 41-send-the-link · Part V · ~1,800 words' },
      { label: 'Chapter count', value: '39 → 41 (+2 this session: Ch 40 Prompting + Ch 41 HTML-ization)' },
      { label: 'Stale-stat sites corrected', value: '11 (across 4 pages)' },
      { label: 'Hanging pages surfaced on homepage', value: '5 (/swarms, /github-playbook, /showcase, /resources, /research-notes)' },
    ],
  },
  {
    edition: 'Edition 9.1',
    date: '2026-05-20',
    tagline: 'Swarms — the deep version, with the skills and the prompts and the receipts.',
    shipped: [
      'New /swarms page (~3,800 words) — the operator\'s deep dive into multi-agent orchestration. Embeds the SwarmVisualizer widget (4 patterns animated: fan-out, pipeline, map-reduce, adversarial). The 5 × 4 wave pattern explained with the real five-wave breakdown from /swarm-strategic-plan.',
      'The skill shelf — 10 swarm skills listed with shape + use case + file path: /swarm-strategic-plan, /debug-swarm, /audit, /agent-wave-verify, /folderly-external-audit, /cross-trio-audit, /bughunter, /ultrareview, /gstack-qa, /gstack-review',
      'Seven swarm patterns from memory — CANON-lock + red-team / design-variant / perspectival editorial / multi-model bake-off / script-not-swarm collector / data-injection-slot / demand-test ≠ build. Each one earned its place by failing first; each gets one paragraph with the receipt.',
      'Three orchestration prompts to steal — the universal subagent dispatch envelope (with the inline-fallback contract), the /audit 6-agent parallel dispatch shape, the BRIEF.md template with HARD CONSTRAINTS section that load-bears across 20 agents',
      'Three things that quietly break a swarm — the 600s watchdog stall, filesystem contention with 5+ agents, load-bearing false premises in the BRIEF. Each one with the fix.',
      '3 ScreenshotPlaceholder slots — tmux running multi-agent dispatch, /swarm-strategic-plan output folder, /agent-wave-verify catching a stub. Placeholders mark intent; screenshots get captured live.',
      'Ch 06 callout — added a tip box at the top of "The Swarm" chapter pointing to /swarms as the deep reference (chapter = story, page = playbook)',
      'Ch 40 cross-link upgraded — the "swarms tease" section in Ch 40 now links to /swarms (was text-only when /swarms didn\'t exist yet)',
      'Cmd-K — /swarms page entry + 10 section anchors searchable',
    ],
    receipts: [
      { label: 'New page', value: '/swarms · ~3,800 words · 10 sections · reuses SwarmVisualizer' },
      { label: 'Skills documented', value: '10 (with paths in ~/.claude/skills/)' },
      { label: 'Swarm patterns codified', value: '7 (each with a failure-receipt origin)' },
      { label: 'Orchestration prompts published', value: '3 (dispatch envelope, /audit shape, BRIEF template)' },
    ],
  },
  {
    edition: 'Edition 9',
    date: '2026-05-20',
    tagline: 'Prompting is basic now. The leverage moved up the ladder.',
    shipped: [
      'New Chapter 40 — "Prompting, or the Knob You Probably Shouldn\'t Tune" (~3,200 words, 12-min read). The contrarian take: prompting is a basic skill now, the real ladder is skills → swarms → memory → data layer. Opens with the verbatim "rigor enforcer" prompt (works, but the wrong leverage) and contrasts it side-by-side with PROMPT_EOD from /resources (the operator-grade shape). Closes with a Monday move: pick the prompt you\'ve tweaked 5+ times and promote it to a skill, schedule, or swarm.',
      'New page /github-playbook — "GitHub for non-developers" (~3,400 words). GH-is-the-new-LinkedIn reframe, 5 non-code uses (private repo as delivery surface, README as living doc, Issues as ops queue, Discussions as forum, Releases as launch posts), the 8 gh commands you actually need, what you can safely ignore (branches, rebasing, merge conflicts, 80% of git), six examples in the wild (Vlad\'s Playbook + AFC + Karpathy/nanoGPT + Simon Willison/TIL + Willison/blog source + GitHub profile README pattern), and the Saturday move.',
      'Ch 40 placed in Part II (Working Memory) — sits next to the vault, skills, build-a-skill, and connectors-MCP chapters. Also added to SECTIONS "claude" topical group.',
      'Cmd-K wired — Ch 40 chapter entry + synonyms (prompting, prompt engineering, chain of thought, ladder, rigor enforcer, etc.), /github-playbook page entry + 8 section anchors searchable',
      'Ch 19 cross-link callout — added a tip box near the gh repo create snippet pointing non-developers to /github-playbook',
      'Fact-checked: nanoGPT marked deprecated by Karpathy in Nov 2025 (still live; example notes the move to nanochat). Originally proposed Patrick Collison reading-list example swapped for Simon Willison blog source (Collison\'s reading list is NOT on GitHub — fact-verified). Anthropic prompting docs URL host updated (docs.anthropic.com → platform.claude.com).',
    ],
    receipts: [
      { label: 'New chapter', value: 'Ch 40 · 40-prompting-knob · Part II · ~3,200 words' },
      { label: 'New page', value: '/github-playbook · 6 examples · 8 gh commands · ~3,400 words' },
      { label: 'Slop catches by research agent', value: '3 (Collison/nanoGPT/gh-pages-flag — all corrected before push)' },
      { label: 'Cross-links wired', value: 'Ch 19 → /github-playbook, Ch 40 → Ch 04/05/06/12/37, /github-playbook → /html-first + /sovereign-stack' },
    ],
  },
  {
    edition: 'Edition 8.2',
    date: '2026-05-20',
    tagline: 'HTML-ization, expanded — the recipe, the gallery, the receipts, the edges.',
    shipped: [
      '/html-first expanded from 4 sections to 9: kept the existing case (AFC + Folderly audit + Do-this-Monday) and added five new ones',
      'New section "More across the portfolio" — the order of operations (pitches first, audits next, internal deliverables third, communication fourth), the one-to-two gap that flips the format from curiosity to default, the Playbook itself as the maximal version of the thesis',
      'New section "The recipe — do this Saturday" — exact verbatim prompt template (12-line constraint block), the four-step ladder (shape → prompt → three iterations → deploy), and the gh-create-repo deploy snippet',
      'New section "Applications gallery" — 12 deliverable shapes that work (audit, pitch, QBR, board, mentee tracker, weekly KPI, financial model, brief, strategy memo, newsletter, conference companion, retro) rendered as a 3-col grid',
      'New section "Not for everything — where this fails" — four honest edges where htmlization should not be used (legal documents, e-signatures, link-averse readers, deploy overhead vs reward)',
      'New section "The pattern in the wild" — 12 public examples sourced (Ciechanowski Moon, Stripe Annual Letter, AI 2027, Anthropic attribution graphs, NYT needle, Ramp benchmarks, a16z market map, Pudding, Bloomberg year-in-graphics, Linear changelog, OWID, Nicky Case) rendered as a clickable 3-col grid with deep links, plus four emerging-pattern paragraphs',
      'SectionNav updated 4 items → 9 items; Cmd-K HTMLFIRST_SECTIONS updated to match for discoverability',
    ],
    receipts: [
      { label: 'Page sections', value: '4 → 9 (+5)' },
      { label: 'New gallery cards (operator applications)', value: '12 shapes' },
      { label: 'New "in the wild" citations', value: '12 sourced public examples, 2024–2026' },
      { label: 'New page weight', value: '+5,500 words approx · still single page, no nav split' },
    ],
  },
  {
    edition: 'Edition 8.1',
    date: '2026-05-20',
    tagline: 'The launch as its own experiment in the thesis.',
    shipped: [
      'New /launch-week page — the launch is its own forwardable artifact. Numbers panel (live GitHub stars, newsletter open rate, subs delta, page-views), a day-by-day timeline of every distribution surface, a "what I\'d do differently" section that populates from real data not Day-0 guesses, a meta-callout explaining why a PDF version would be obsolete the second it was exported',
      'src/lib/launch-week.ts — single source of truth for the timeline + numbers + retrospective; append-only daily edits (one-line additions, no schema breaking)',
      'Day-0 distribution drafts authored locally (notes/launch/, gitignored): 8-tweet X thread (each tweet stands alone), LinkedIn longform (founder-realization frame), Hacker News Show HN (title + first-comment), Day-7 Numbers newsletter template with TBD slots',
      'Homepage tile grid restored to 4-up across multiple rows — 8 tiles: Sovereign Stack · HTML-ization · The launch · Launch week · Vault library · Cheat sheet · Glossary · Tier list. About moved to the small text-link below.',
      'Cmd-K indexes /launch-week as a discoverable destination',
    ],
    receipts: [
      { label: 'New page', value: '/launch-week' },
      { label: 'Distribution surfaces drafted', value: '4 (Newsletter · X · LinkedIn · HN)' },
      { label: 'Homepage tiles', value: '4 → 8 (2 rows of 4)' },
      { label: 'Day-7 follow-up scheduled', value: 'Numbers post — receipts of launch week, sent regardless of how it goes' },
    ],
  },
  {
    edition: 'Edition 8',
    date: '2026-05-20',
    tagline: 'Two stacks, not one. The sovereign tier is built.',
    shipped: [
      'New /sovereign-stack page — the open-weights answer to the deprecation calendar. The Onyx Open-Source LLM Leaderboard rebuilt as a tier list (Overall / Coding / Math / Chat / Reasoning), Ollama vs LM Studio vs vLLM, five hardware tiers ($2k MacBook → $40k+ deploy) with what-breaks-first per tier, quantization + KV-cache math, open-vs-closed cost-per-task table (30× ratio on repeated evals), the heretic question (abliteration framed as sovereignty, not jailbreaking), the Mythos lesson, Karpathy nano-gpt as a Saturday curriculum, the 6-month watch list',
      'New OnyxLeaderboard.tsx widget — interactive S/A/B/C/D tier list with category tabs, size filters (Small/Medium/Large by parameter count), and per-lab filters showing the Chinese-lab dominance of the open-weights frontier (6/6 S-tier slots)',
      'New glossary terms — Sovereign stack · Heretic model · Mythos · Abliteration — all cross-linked',
      'Ch 24 (tier-list) callout pointing to /sovereign-stack — the closed-model tier list and the open-weights tier list now talk to each other',
      'Homepage tile grid rebalanced — Sovereign Stack takes flagship-first position (4 across), Glossary + tier-list + launch + about demoted to a single text row of secondary links below the grid',
    ],
    receipts: [
      { label: 'New page', value: '/sovereign-stack' },
      { label: 'Leaderboard snapshot', value: 'Onyx Open-Source LLM Leaderboard · 2026-03-24 · 19 models across 5 categories' },
      { label: 'Sourced citations', value: '60+ inline links — Arditi 2024, modded-nanogpt, Onyx, Ollama MLX, all model releases' },
      { label: 'Open-weights S-tier (May 2026)', value: 'GLM-5 · Kimi K2.5 · MiniMax M2.5 · DeepSeek V3.2 · Step-3.5-Flash · Qwen 3.5' },
    ],
  },
  {
    edition: 'Edition 7',
    date: '2026-05-20',
    tagline: 'The book is open. The source is the recipe.',
    shipped: [
      'Repo flipped to public after a full git-filter-repo history scrub — 71 commits rewritten, 0 leaks across blobs and commit messages from an independent fresh-clone verification, backup ref preserved server-side',
      'New /launch page — the launch artifact IS the demo: typewriter hero, animated stat odometer (chapters/widgets/glossary/embeds/editions/stars), the 3 live embedded case studies, all 39 chapters as a click-anywhere mosaic, what-it-took timeline, post-credit AFC tease',
      'Homepage "Now" banner above the tile grid promoting the launch through launch week',
      'README rewrite to current reality (Edition 6/7, real counts, dive.vladyslavpodoliako.com as primary CTA), repo metadata (description, homepage, 12 topics, Discussions on), custom 1280x640 GitHub social-preview image',
      'SECURITY.md + CONTRIBUTING.md refreshed for the public posture; private-vulnerability-reporting path documented',
      'Ch 02 contradiction fixed (the Fathom-in-the-don\'t-use-bin error caught externally) — reframed as "picked Fathom, killed the rest" with the discipline of one transcript surface',
    ],
    receipts: [
      { label: 'Repo state', value: 'PUBLIC · github.com/Belkins/ai-dive-deep' },
      { label: 'History leaks (post-scrub, fresh-clone verified)', value: '0 / 71 commits' },
      { label: 'New page', value: '/launch' },
      { label: 'Edition 1 → public', value: '13 days, 7 editions' },
    ],
  },
  {
    edition: 'Edition 6',
    date: '2026-05-19',
    tagline: 'The method, embedded. Click the artifacts.',
    shipped: [
      'New /html-first page — the htmlization thesis (every deliverable ships as a live interactive artifact, not a dead file) with two REAL artifacts embedded and clickable',
      'AFC case: the dinner-table idea whose investment deck + robot-stable annex got spun up as interactive HTML before the next meeting — Vlad\'s own venture, embedded as-is',
      'Folderly case: a real ~90-domain / ~5K-mailbox external deliverability audit, swarm-produced on the Folderly methodology — fully de-identified (client, all 90 domains, SPF/infra fingerprints, WHOIS name) and embedded as a sanitized sample',
      'New ArtifactEmbed.astro — sandboxed, lazy, render-on-click iframe modal (no src until opened; referrerpolicy=no-referrer)',
      'Ch 19 callout + glossary "Htmlization" + Cmd-K (page + 4 section anchors) wired',
    ],
    receipts: [
      { label: 'Live artifacts embedded', value: '3 (AFC ×2, audit ×1)' },
      { label: 'Folderly identifiers redacted', value: '90 domains + name + 2 SPF + WHOIS → 0 residual' },
      { label: 'New page / component', value: '/html-first + ArtifactEmbed' },
      { label: 'External calls in embeds', value: '0 (fully self-contained)' },
    ],
  },
  {
    edition: 'Edition 5',
    date: '2026-05-19',
    tagline: 'The bench moved. The reports stopped being files.',
    shipped: [
      'Gemini 3.5 Flash + Claude-for-the-legal-industry logged as dated research notes — signal-vs-receipt discipline, not a leaderboard edit',
      'Ch 35: corrected the stale "Gemini 3 Pro" reference + added the Flash-beats-last-gen-Pro signal, scoped as a Ch 29 cost question rather than a re-tiering',
      'Ch 29: new section — "The price of a model is not the price of a task" + a cost-per-task test loop you run on your own traffic',
      'Ch 24: May-2026 addendum extended; the live LMArena widget stays the source of truth — no slide-driven tier edits',
      'New thesis across Ch 19 / Ch 26 / About — every report ships as a living link on a private repo, not a dead file; unsanctioned copying as the truest adoption metric',
    ],
    receipts: [
      { label: 'Research notes added', value: '2' },
      { label: 'Chapters touched', value: '19, 24, 26, 29, 35' },
      { label: 'Live bench edits', value: '0 (signal, not receipt)' },
      { label: 'New components', value: '0' },
    ],
  },
  {
    edition: 'Edition 4',
    date: '2026-05-11',
    tagline: 'Retitled for navigation. Voice survived.',
    shipped: [
      'All 36 chapter titles rewritten — topical-primary, with question form on 9 chapters where intent shape beats subject shape',
      'Old hype titles preserved as subtitles ("The Day I Killed My Tabs" now sits below "AI as an Operating System")',
      'Cmd-K resolves "cron" → Scheduled Tasks, "browser" → Browser Agents with Playwright, "permissions" → When to Skip Permissions',
      'scripts/apply-titles.py — atomic re-runnable rewrite of all 36 frontmatters + chapters.ts. Re-run any time the map changes.',
    ],
    receipts: [
      { label: 'Chapters retitled', value: '36' },
      { label: 'Time to scan TOC', value: '~6s → ~2s' },
      { label: 'Voice lines lost', value: '0' },
    ],
  },
  {
    edition: 'Edition 3.5',
    date: '2026-05-09',
    tagline: "Repo flipped private. Site stayed public.",
    shipped: [
      'Repo visibility flipped to PRIVATE (Belkins on GH Pro tier)',
      'Issues, Wiki, Projects, Discussions disabled — attack surface reduced',
      'SECURITY.md committed with vulnerability reporting + ops rules',
      '.gitignore hardened — .pem, .key, .aws/, .kube/, secrets/, .vercel',
      'Vercel fallback config committed — dual-target astro.config.mjs reads DEPLOY_TARGET env',
      'Vercel security headers baked (HSTS, X-Frame-Options DENY, X-Content-Type-Options, Permissions-Policy)',
    ],
    receipts: [
      { label: 'Repo visibility', value: 'PUBLIC → PRIVATE' },
      { label: 'Site downtime during flip', value: '~3 min (Pages re-enable required)' },
      { label: 'Surfaces disabled', value: '4' },
    ],
  },
  {
    edition: 'Storytelling layer',
    date: '2026-05-08',
    tagline: '36 islands became one six-act journey.',
    shipped: [
      '/how-to-read — ~1,100-word prologue. Who this is for, the reframe, the journey, three ways to use the book.',
      '/journey — 6-part narrative arc (Reframe → Memory → Workshop → Discipline → Building → Frontier)',
      '/questions — 18 questions Vlad answers most weeks, each with short answer + chapter pointers',
      'Part pill on every chapter hero — readers know where they are in the arc',
      'Chapter footer transitions detect part boundaries: "Next: Part III — The Workshop →"',
      '/showcase — auto-extracted from ~/.claude/: 62 skills + 32 custom agents + 12 plugins, categorized + searchable',
      '/cowork-setup — sanitized: 12 connector categories + 8 scheduled-task patterns + day-shape timeline. Zero local-data scan.',
    ],
    receipts: [
      { label: 'Reader-facing pages added', value: '+5' },
      { label: 'Skills surfaced', value: '62' },
      { label: 'Sensitive paths read', value: '0 (Cowork showcase derived from published chapters)' },
    ],
  },
  {
    edition: 'Edition 3',
    date: '2026-05-07',
    tagline: 'Closed the original brief. Six new chapters, two new pages.',
    shipped: [
      'Ch 31 — The Stages: Ideation → Foundation → Creation → Polishing → Security → Deploy',
      'Ch 32 — How to Build Rick (OpenClaw, NemoClaw, Hermes archetypes)',
      'Ch 33 — Browser Agents with Playwright (login, click, scrape, post)',
      'Ch 34 — Persona Agents and the Four NEVERs',
      'Ch 35 — Codex × Claude Code (day shift, night shift)',
      'Ch 36 — Beyond Claude Code (CrewAI, LangGraph, SDK)',
      'StagesFlow widget (Ch 31) — six clickable stages with artifact + ready test + failure mode',
      'ArchetypePicker widget (Ch 32) — 3-question intake → recommended Rick archetype + install command',
      '/day-zero — literal first 30 minutes with 12 localStorage-persisted checkboxes',
      '/sections — chapters grouped by General / Claude / Security / AI Agents / Building / Team+Tier',
    ],
    receipts: [
      { label: 'Chapters added', value: '+6 (30 → 36)' },
      { label: 'Widgets added', value: '+2 (12 → 14)' },
      { label: 'New pages', value: '+2 (/day-zero, /sections)' },
    ],
  },
  {
    edition: 'Edition 2',
    date: '2026-05-07',
    tagline: 'Fixed the muscles. Wrote the spine.',
    shipped: [
      '6 new chapters (Ch 25-30): Evals, Team Adoption, Voice Agents, Failure Receipts, Cost Economics, Anthropic SDK Direct',
      '4 new widgets: TokenBurnCalculator (Ch 2/29), TempAgencyLoop (Ch 3), VaultGraphPreview (Ch 4), HookEventTimeline (Ch 16)',
      '12 a11y + UX patches: glossary popovers via Radix (no more navigate-away mid-read), focus rings, skip-to-content, paper contrast fix, 17px body on ≥640px, anchor links on H2/H3, print stylesheet',
      '10 new operator prompts added to /resources: deal post-mortem, hire screen, model migration, board update, mentee prep, RFP triage, kill decision, customer-call synthesis, writing-filter, Tuesday-9am triage',
      'ResumeReading pill on landing (localStorage-driven)',
      'Substack subscribe iframe in footer',
      'Sharper "Most readers go here next" copy in chapter footer',
    ],
    receipts: [
      { label: 'Chapters', value: '24 → 30' },
      { label: 'Widgets', value: '8 → 12' },
      { label: 'Pages', value: '32 → 38' },
    ],
  },
  {
    edition: 'Edition 1',
    date: '2026-05-07',
    tagline: 'The book became an artifact.',
    shipped: [
      '24 chapters migrated from .docx into MDX (4 parallel agents, partitioned by chapter range)',
      '8 interactive widgets: StackSelector, SwarmVisualizer, CronBuilder, ModePicker, SkillComposer, ConnectorMap, PermissionSimulator, TierListBuilder',
      'Cmd-K command palette + dark theme + view transitions + reading progress bar',
      'Resources page with copy-paste vault library: CLAUDE.md skeleton, .mcp.json examples, hook scripts, SKILL templates, 5 reusable prompts',
      'Printable cheat sheet (Ch 14, @media print styled)',
      '30-day plan generator (3 intake questions → custom 30-day calendar, .ics + markdown export)',
      'Drag-and-drop tier list builder with shareable URL hash',
      'GitHub Pages deployment via Actions; live in ~50s per push',
    ],
    receipts: [
      { label: 'Source words migrated', value: '~43,000' },
      { label: 'Parallel agents in chapter migration', value: '4' },
      { label: 'Wall-clock for full Edition 1 build', value: '~3 hours' },
      { label: 'Dist size', value: '1.4 MB / 32 pages' },
    ],
  },
];
