// Edition timeline. Update when shipping a new edition.

export type ChangelogEntry = {
  edition: string;
  date: string;        // ISO yyyy-mm-dd
  tagline: string;
  shipped: string[];
  receipts?: { label: string; value: string }[];
};

export const CHANGELOG: ChangelogEntry[] = [
  {
    edition: 'Edition 10.0',
    date: '2026-06-09',
    tagline: 'Fable 5 / Mythos 5 — the withheld model shipped, and the Playbook files it the day it lands: a research note that corrects the May 6 call, a nine-page model file, and the three evergreen pages the keyword map has been waiting for.',
    shipped: [
      'New research note (top of the timeline) — "Fable 5 / Mythos 5 — the withheld model shipped, split in two." The May 6 note read the Mythos disclosure as a capability ceiling Anthropic would not productize; the correction is the mechanism nobody predicted: one model, two names (Latin fabula / Greek mythos), the raw twin gated behind Project Glasswing, the safeguarded twin sold to everyone at $10/$50 per Mtok with classifier fallback to Opus 4.8.',
      'New model file: /fable-5 — a hub plus eight spokes, each owning one question. vs-mythos-5 (one model, two names, three safeguards), benchmarks (the full 13-row launch table with the Berkeley-RDI discount applied), vs-opus-4-8 (upgrade or wait), vs-gpt-5-5 (cross-vendor, incl. Gemini 3.1 Pro), pricing (sticker vs cost-per-task), use-cases (Stripe\'s 50M-line day, drug design, genomics — vendor-curated and labeled as such), claude-code (the banner, the June 22 clock, the routing), api (claude-fable-5, the one new 400).',
      'The two launch demos embedded — Fable 5 beating Pokémon FireRed on raw screenshots (vision only, no maps, no navigation aids — previous Claude models could not finish it even with helper harnesses) and the solar-system/eclipse simulation.',
      'The developer-facing fine print folded in: blocked API requests return an unbilled error with fallback-to-Opus-4.8 opt-in at Opus pricing (built into the apps and Managed Agents); Fable 5 as an advisor model — cheap workers call it mid-task to check plans, the book\'s conductor-and-judge split as an API primitive; the 30-day misuse-only retention and the Console terms gate.',
      'Three evergreen pages from the SEO/AEO keyword map, every claim chapter-sourced: /claude-code-best-practices (the practices that survived production, distilled from 45 chapters), /claude-code-vs-cursor (the comparison the answer engines currently source from Reddit), /what-is-agentic-coding (the operator\'s definition, with the 90k-line worked example).',
      'Full wiring — homepage model-file tile, mobile-nav entries, 12 Cmd-K entries, four glossary terms (Fable 5, Mythos 5, Mythos-class, and a disambiguated Mythos), three new inbox questions with FAQPage schema, llms.txt entries for every new page, and this changelog.',
    ],
    receipts: [
      { label: 'New pages', value: '12 — /fable-5 hub + 8 spokes + 3 evergreen' },
      { label: 'The model', value: 'claude-fable-5 · $10/$50 per Mtok · 1M context' },
      { label: 'The correction', value: 'May 6 "Mythos isn\'t coming" → it came, split in two' },
      { label: 'The clock', value: 'included in plan limits Jun 9–22, then usage credits' },
    ],
  },
  {
    edition: 'Edition 9.9',
    date: '2026-06-08',
    tagline: 'Forty-five chapters. The App Store Without Swift — Claude Code one-shot a native iOS app for LinguaLive, and shipping it to the App Store meant walking through the gates the operator, not the agent, has to own. The proof is a RevenueCat renewal, read honestly.',
    shipped: [
      'New Chapter 45 — "The App Store Without Swift" (Part V, The Building Site; Building Products section). The apex of the build-a-product arc: Claude Code one-shot every line of native SwiftUI for LinguaLive and still could not ship it. The App Store is just another deploy target — with the strictest gates in the book, and the operator owns every one: a Mac + Xcode, the $99/yr Developer Program, the signing maze, account deletion (Guideline 5.1.1(v)), the App Privacy label, and a working demo login for the reviewer.',
      'The reframe, Ch 43-style: the lesson is not "you can build iOS without Swift" — the code is the easy part now. It is that shipping native means owning the platform-and-policy surface the agent is structurally locked out of. Ties straight to Ch 41 (proof is a live artifact, not a file) and Ch 43 (verify with real behavior is the whole game).',
      'The proof is recurring revenue, read honestly. Real App Store numbers — LinguaLive Monthly Pro $7.99 and Pro Annual $79.99, an INITIAL_PURCHASE that became a RENEWAL — recreated as an on-brand dashboard that teaches the reader to read it without inflating it: a RENEWAL is recurring revenue not a new customer, $RCAnonymousID is an anonymous buyer not a redaction, the dollars are gross estimates not a bank deposit, and the row proves recurring revenue and a stacking renewal, NOT total scale. Apple\'s cut is stated correctly (never a flat 30% — 30% year one, 15% after, or 15% flat under the Small Business Program).',
      'Three house-style inline SVG diagrams (palette-correct, librsvg render-verified, mobile-legible): the receipt read honestly, the agent-owns-the-code / operator-owns-the-gates map, and the web→native arc tracing one dollar from a real-phone tap through StoreKit and Apple to the dashboard row.',
      'Built by the deep multi-agent workflow chain — a four-researcher swarm verified the App-Store-without-Swift reality against Apple\'s own docs (signing, IAP / Guideline 3.1.1, account deletion, the tiered commission, RevenueCat) plus a completeness critic, then a three-perspective design swarm (reframe / receipts / journey) reconciled by a synthesis judge. Every platform fact is primary-sourced; every lived LinguaLive number is sourced or left to the author, never invented.',
      'Wiring — chapters.ts (CHAPTERS + Part V + the Building section), Cmd-K synonyms, and this changelog. Chapter-count stat swept 44 → 45 across the user-facing pages and the lint-invisible OG/ad cards (og-default, og-launch, the −90k ad).',
    ],
    receipts: [
      { label: 'New chapter', value: 'Ch 45 · 45-app-store-no-swift · Part V — The Building Site' },
      { label: 'Subject', value: 'LinguaLive — native iOS, App Store, real recurring revenue' },
      { label: 'Proof', value: 'RevenueCat renewal · $7.99/mo + $79.99/yr · read honestly' },
      { label: 'Built by', value: 'research swarm (Apple-sourced) → design swarm → synthesis' },
    ],
  },
  {
    edition: 'Edition 9.8',
    date: '2026-06-05',
    tagline: 'Learn — the on-ramp before the book. A new /learn page routes total beginners through the official free courses, in order, then hands them to the Playbook.',
    shipped: [
      'New standalone page /learn — the entry point for anyone new to AI, Claude, Claude Code, or Cowork. A staged learning ladder (concepts → official courses → orient + set up → read and build), a five-word concepts primer that links the glossary instead of redefining it, and a no-code vs builder split that meets back up at the end.',
      'The full official course catalog, verified live and ordered — not dumped. Anthropic Academy first (Claude 101, Claude Code 101, Cowork, Agent Skills, Subagents, the Claude API, MCP, docs + cookbooks), then OpenAI and Google official academies, then hand-picked independents (DeepLearning.AI, Hugging Face, Microsoft). 28 resources; only the 3-card foundation shows by default, the rest behind drawers so it never becomes a wall.',
      'Four house-style inline SVG diagrams (palette-correct, viewBox-only, mobile-legible): the learning ladder, chatbot-vs-OS, the agent loop, and the ecosystem map. A "what you will build" section points at real receipts (the HTML-ization weekend, the one-day product, the twelve-file workflow refactor) plus Anthropic\'s own customer numbers.',
      'Designed and built by a deep multi-agent workflow — research across every vendor learning ecosystem (links HTTP-verified), curriculum + IA + diagram design, Vlad-voice copy, then an adversarial red-team that cut a mis-sourced stat, two stale "free" cards, and a 31-card wall before any of it shipped.',
      'Wiring — new Learn tab in the nav, a flagship homepage tile + hero CTA, Cmd-K entry + section deep-links + popular default, and this changelog. Chapter count unchanged.',
      'Fact-checked post-ship — all 28 course/resource links re-verified live; corrected the Satispay descriptor (the headcount was not on the cited source), reframed the one-day build to the honest "shipped in a Saturday" per Ch 19, added paid-plan/beta caveats to the Cowork + two DeepLearning.AI cards, and added a "stuck? paste the error back into Claude" line.',
    ],
    receipts: [
      { label: 'New page', value: '/learn · onboarding on-ramp · 7 sections, 4 diagrams' },
      { label: 'Courses', value: '28 verified-live (Anthropic · OpenAI · Google · independents)' },
      { label: 'Built by', value: 'deep multi-agent workflow + adversarial red-team' },
      { label: 'Wiring surfaces', value: 'Nav · homepage tile + hero CTA · Cmd-K · changelog' },
    ],
  },
  {
    edition: 'Edition 9.7',
    date: '2026-06-04',
    tagline: 'Forty-four chapters. Dreaming — the autonomous loop pointed inward: a local, propose-only twin of Anthropic\'s memory feature that surfaces candidate lessons from your own sessions and verifies every quote against the raw transcript, but never writes to memory itself.',
    shipped: [
      'New Chapter 44 — "Dreaming — Memory That Curates Itself" (Part II, Working Memory; also in the General + Claude sections). The curation layer Ch 37 leaves open: it teaches the four memory layers but never how memory stays deduped, true, and under its bloat ceiling across hundreds of sessions. Dreaming is that loop — and the one autonomous loop in the book that is structurally forbidden to write.',
      'New standalone page /dreaming — the operator runbook: the five-stage pipeline (select → digest → extract → verify → review, and only extract is the model), the five refusals, the receipts, the data-locality "exception to Chapter 7" (why you never cloud-cron a local-disk corpus), and when not to run it.',
      'The thesis — every autonomous loop in the Playbook points outward (the swarm reads the codebase, cron reads the calendar, run-until-done reads the task); Dreaming is the first pointed at the agent\'s own memory, so it gets less rope, not more. Propose-only is the ceiling, not just the default: the most the pipeline can do is write one review file a human acts on via /learn.',
      'Receipts, stated honestly — two real runs: single-project (3 sessions → 3 candidates → 3 verified) and cross-project (6 sessions across 3 projects → 15 candidates → 15 verified, 0 dropped, 14 net-new, 1 the tool flagged as a duplicate). The failure kept in: it caught the dup it could see (against the portfolio index) and honestly missed two that lived one level down in a project\'s own memory — the design\'s open question #10, confirmed in the wild on run one.',
      'The method shown — Chapter 44 and the page were themselves planned by an 8-agent design swarm (five perspective architects → reconciler + red-team → synthesis); the red-team caught and corrected an over-stated receipt against disk before it could ship. Two real /workflows screenshots wired in.',
      'Full 6-surface wiring — chapter + page, Cmd-K entry + section deep-links + synonyms, glossary terms (Dreaming, Agent memory, Memory curation, Propose-only), homepage flagship "Memory" tile, llms.txt + entity graph (author knowsAbout), and this changelog. Chapter-count stat swept 43 → 44 across the user-facing pages.',
    ],
    receipts: [
      { label: 'New chapter', value: 'Ch 44 · 44-dreaming · Part II — Working Memory' },
      { label: 'New page', value: '/dreaming · pipeline + 5 refusals + receipts + runbook' },
      { label: 'Chapter count', value: '43 → 44' },
      { label: 'The run', value: '6 sessions · 15 verified · 0 dropped · 14 net-new · 1 flagged dup' },
      { label: 'Glossary terms', value: 'Dreaming · Agent memory · Memory curation · Propose-only' },
    ],
  },
  {
    edition: 'Edition 9.6',
    date: '2026-05-28',
    tagline: 'Dynamic Workflows — a standalone page on Opus 4.8\'s headline feature: the swarm that runs itself.',
    shipped: [
      'New standalone page /dynamic-workflows — Opus 4.8 ships dynamic workflows: Claude writes a JS script that plans a big task, fans out up to 16 parallel subagents (1,000 per run), runs an adversarial verifier pass, and reports one answer. Part explainer (what it is, agent-teams vs workflows, the generator->validator loop), part operator\'s read, part reference.',
      'The validator loop is the spine — one set of agents builds, another tries to break it, a fixer closes the gap. The /effort dial + ultracode are the on-ramp (ultracode = xhigh + automatic workflow orchestration). With a first-person take and a "when not to run a workflow" section so it reads as judgment, not hype.',
      'Receipts over claims — every number is from Anthropic\'s announcement or the Claude Code docs (16 concurrent / 1,000 per run, research preview, v2.1.154+, the Bun Zig->Rust port: 750k lines in 11 days at 99.8% tests). The /effort slider screenshots + a clip of the dial in motion + a house-style agent-teams-vs-workflows diagram.',
      'Full 6-surface wiring — page, Cmd-K entry + section deep-links, Ch 40 cross-link, glossary terms (Dynamic workflows, Agent teams, /effort, ultracode), homepage flagship tile, and this changelog entry.',
    ],
    receipts: [
      { label: 'New page', value: '/dynamic-workflows · explainer + operator read + reference' },
      { label: 'Glossary terms', value: 'Dynamic workflows · Agent teams · /effort · ultracode' },
      { label: 'Scale documented', value: '16 concurrent · 1,000 agents / run' },
      { label: 'Wiring surfaces', value: '6/6' },
    ],
  },
  {
    edition: 'Edition 9.5',
    date: '2026-05-23',
    tagline: 'Forty-three chapters. The Codex loop from Ch 42 runs for real — a 90,000-line product refactor, proof-checked.',
    shipped: [
      'New Chapter 43 — "Codex as Saviour" (~2,390 words, 13-min read). The full-scale payoff of Ch 42\'s standing loop ("simplify, follow my design system"): pointed at a real shipping product (Folderly Email Generator), a bench of fourteen named explorer agents deleted a net 91,874 lines across 718 files, repositioned the product from seven surfaces to one promise, and HARDENED the risky paths the simplification exposed — all behind real build, CI, browser, and API checks. The thesis: simplification and security are the same phase.',
      'The numbers, reconciled — hero stat is the final shipped release (718 files, +43,092 / −134,966, net −91,874, 243 commits, 106 begin with "Simplify", 27 hardening). The mid-run screenshot counter (585 files / +30,928 / −55,984) is framed explicitly as the diff mid-flight before the branch finished, not a contradiction. Plus the real cost receipt — 46% of one week\'s usage — and the human-steer receipt: the operator told the loop to checkpoint mid-run ("test the build, commit and push if no regressions").',
      'The bench — the literal swarm (Pauli, Planck, Hume, Ramanujan, Averroes, Gibbs, Fermat, Sagan, Hooke, Socrates, Feynman, Beauvoir, Franklin, Mill) mapped onto a conceptual ten-lens decision model with veto power. The insight you steal: the lenses disagree productively — a delete that helps UX can hurt SEO, a security fix can break an integration — so the swarm forces each tradeoff explicit before code lands. Cross-links Ch 6 (the swarm).',
      'The paste-able artifact — the eight-phase simplification playbook as a copy-paste block (name the product in one sentence → split the surface into four buckets → preserve before pruning → reduce first-use decisions → move power behind intent → delete by category → harden while simplifying → ship in verified layers).',
      'Harden while simplifying — Phase 7 written as a generalized bug-class checklist an operator runs on ANY product (does a route mutate on GET? are OAuth states signed? are entitlements server-side? do protected APIs return JSON 401 or a confusing redirect? does cron auth fail closed?), not a Folderly incident report. Sanitized for public publication.',
      'Four authored house-style SVG diagrams (the dark/orange book palette crossed with Folderly blue #195EE6 to encode before→after): the bench roster + veto lenses + the Emberling pet from Ch 42, the seven-surfaces→one-promise repositioning, the delete-by-the-numbers stat card, and the four-bucket surface split.',
      'Placed in Part VI (Frontier + Tier) next to Ch 35 and Ch 42, and in the SECTIONS "AI agents" group. Cmd-K entry + synonyms. Three inbound cross-links so Ch 43 is a node, not a dead end: Ch 42 (the pet-joke payoff — "the loop actually ran it"), Ch 35 (the full-scale receipt of the day/night-shift loop), Ch 38 (what the fence looks like at 90,000 lines).',
      'Executed as a swarm — voice-calibrated drafting agent (read Ch 35/42/38/6 first) + parallel SVG authoring + adversarial proof-check. Chapter-count stat swept 42 → 43 across the user-facing pages.',
    ],
    receipts: [
      { label: 'New chapter', value: 'Ch 43 · 43-codex-saviour · Part VI · ~2,390 words' },
      { label: 'Chapter count', value: '42 → 43' },
      { label: 'The delete', value: '718 files · net −91,874 lines · 243 commits' },
      { label: 'Authored diagrams', value: '4 house-style SVGs (book palette × Folderly blue)' },
    ],
  },
  {
    edition: 'Edition 9.4',
    date: '2026-05-21',
    tagline: 'Forty-two chapters. Codex gets the hands-on companion — second opinion, on a loop, proof-checked.',
    shipped: [
      'New Chapter 42 — "Codex on a Loop" (~1,950 words, 11-min read). The hands-on companion to Ch 35\'s strategic day-shift/night-shift framing. The thesis: Codex isn\'t a better Claude Code, it\'s a second prior I run on a loop — pointed at Sentry (errors), PostHog (funnel-drop anomalies), and BetterStack (uptime/log alerts) via MCP + crons, fixing fresh signals in worktree-isolated PRs, and proof-checking the day driver\'s diffs by running the tests CC didn\'t think to run.',
      'The honest framing — explicit "this is NOT Codex beats Claude Code" callout that defers the ranking to /tier-list. Same second-prior logic as the Gemini argument in Ch 35: the value is the delta, never the leaderboard.',
      'The loop, with a fence — the standing `/loop` prompt ("simplify, follow my design system") plus the discipline that makes it safe: an evaluator that says stop (cross-link Ch 38) and a diff ceiling that caps blast radius. A four-file simplification is a fix; a nine-file one is a re-architecture wearing a fix\'s clothes.',
      'Proof-checking as the whole discipline — two levels: Codex proof-checks CC\'s PRs (machine), the human proof-checks the loop (judgment). Best execution = a second opinion plus a proof check, never one agent trusted blind.',
      'Ten minutes to a desktop pet — the fun payoff and the lightest proof the cross-vendor SKILL.md claim holds: handed Codex the `hatch-pet` skill + a one-line cyberpunk brief, it read the contract, generated + self-validated sprite assets in a worktree, and hatched "Emberling" — a half-robot/half-flame desktop pet — in ~10 minutes. 4 real screenshots wired in (Codex conversation, contact sheet, live animation gif, pet-on-desktop).',
      'Placed in Part VI (Frontier + Tier) next to Ch 35, and in the SECTIONS "AI agents" topical group. Cmd-K entry + synonyms (codex loop worktree sentry posthog betterstack proof-check pet emberling hatch-pet second opinion).',
      'Executed as a swarm — voice-calibrated drafting agent + adversarial proof-checking pass. The chapter keeps its own receipt: it says so in the text.',
      'Consistency pass — chapter-count stat swept 41 → 42 across 5 user-facing pages (homepage header + Now banner + launch tile, /journey, /sections, /launch, /github-playbook). Two copy-pasteable artifacts added to Ch 42 (the LinguaLive product-analytics .mcp.json; the worktree + fenced /loop commands). Three inbound cross-links added so Ch 42 is a node, not a dead end: Ch 38 (a real /loop example), Ch 39 (the hatch-pet cross-vendor receipt), Ch 20 (worktree-per-fix in practice). The last screenshot slot filled with a house-style loop-flow diagram.',
    ],
    receipts: [
      { label: 'New chapter', value: 'Ch 42 · 42-codex-on-a-loop · Part VI · ~1,950 words' },
      { label: 'Chapter count', value: '41 → 42' },
      { label: 'Real screenshots added', value: '4 (hatch-pet conversation, contact sheet, Emberling gif, desktop pet)' },
      { label: 'Emberling gif weight', value: '3.8 MB → 2.4 MB (gifsicle -O3 --lossy)' },
    ],
  },
  {
    edition: 'Edition 9.3',
    date: '2026-05-20',
    tagline: 'Every page one click from the homepage. Tile grid grows to 3 rows.',
    shipped: [
      'Homepage tile grid expanded from 8 → 12 tiles (3 rows of 4). Row 3 added: Swarms · GitHub Playbook · Setup showcase (62 skills · 32 agents · 12 plugins) · Research notes (what shifted this week). The pages I shipped this week are now first-class tiles, not secondary-row text links.',
      'Hanging-pages cleanup — secondary text row rewritten to surface the remaining 10 previously-hanging pages: Build vs Buy · For your CFO · CLAUDE.md rules · Cowork setup · Vault starter · Weekend builds · Starter skills · 30-day plan · Sections · About. Every standalone page in the Playbook is now one click from the homepage.',
      'Reachability audit complete — 27 user-facing pages audited (plus /the-bill which is intentionally sitemap-excluded). Zero orphans, zero hanging-from-homepage pages remain.',
    ],
    receipts: [
      { label: 'Homepage tiles', value: '8 → 12 (+4 third-row tiles)' },
      { label: 'Pages reachable from homepage', value: '13 → 27 (every page surfaced)' },
      { label: 'Hanging pages (after audit)', value: '0 (was 9 pre-audit)' },
      { label: 'Orphans', value: '1 — /the-bill, intentional sitemap exclusion' },
    ],
  },
  {
    edition: 'Edition 9.2',
    date: '2026-05-20',
    tagline: 'Forty-one chapters. The HTML-ization thesis gets its own chapter slot.',
    shipped: [
      'New Chapter 41 — "Send the Link, Not the File" (~1,800 words, 9-min read). Chapter-length narrative companion to /html-first. The story version of the HTML-ization thesis: every report, pitch, audit, deck, model in the portfolio ships as a live interactive link in a private repo, not a PDF or slide attachment. Same recipe across the portfolio; the chapter tells the story, /html-first is the deep reference with the embedded case studies, the recipe, the gallery, and the 12 public examples in the wild.',
      'Ch 41 placed in Part V (Building Site) — sits next to Ch 19 (Saturday builds), Ch 31 (six stages), Ch 38 (run until done). Also in SECTIONS "building" topical group.',
      'Cmd-K — Ch 41 chapter entry + synonyms (html htmlization living-link artifact deploy private repo afc folderly qbr board update)',
      'Hanging-pages audit + homepage secondary text row expanded — surfaced /swarms, /github-playbook, /showcase, /resources, /research-notes alongside /about. Five previously-hanging pages now one click from the homepage.',
      'Stale "39 chapters" → "41 chapters" across 11 user-facing sites: homepage hero stat ("39 chapters"), homepage section header ("Thirty-Nine Chapters" → "Forty-One Chapters"), Now banner copy, launch-tile description, /journey description meta + body, /sections description meta + body, /launch description meta + body, /github-playbook example card. Historical changelog entries kept original count (accurate at the time).',
    ],
    receipts: [
      { label: 'New chapter', value: 'Ch 41 · 41-send-the-link · Part V · ~1,800 words' },
      { label: 'Chapter count', value: '39 → 41 (+2 this session: Ch 40 Prompting + Ch 41 HTML-ization)' },
      { label: 'Stale-stat sites corrected', value: '11 (across 4 pages)' },
      { label: 'Hanging pages surfaced on homepage', value: '5 (/swarms, /github-playbook, /showcase, /resources, /research-notes)' },
    ],
  },
  {
    edition: 'Edition 9.1',
    date: '2026-05-20',
    tagline: 'Swarms — the deep version, with the skills and the prompts and the receipts.',
    shipped: [
      'New /swarms page (~3,800 words) — the operator\'s deep dive into multi-agent orchestration. Embeds the SwarmVisualizer widget (4 patterns animated: fan-out, pipeline, map-reduce, adversarial). The 5 × 4 wave pattern explained with the real five-wave breakdown from /swarm-strategic-plan.',
      'The skill shelf — 10 swarm skills listed with shape + use case + file path: /swarm-strategic-plan, /debug-swarm, /audit, /agent-wave-verify, /folderly-external-audit, /cross-trio-audit, /bughunter, /ultrareview, /gstack-qa, /gstack-review',
      'Seven swarm patterns from memory — CANON-lock + red-team / design-variant / perspectival editorial / multi-model bake-off / script-not-swarm collector / data-injection-slot / demand-test ≠ build. Each one earned its place by failing first; each gets one paragraph with the receipt.',
      'Three orchestration prompts to steal — the universal subagent dispatch envelope (with the inline-fallback contract), the /audit 6-agent parallel dispatch shape, the BRIEF.md template with HARD CONSTRAINTS section that load-bears across 20 agents',
      'Three things that quietly break a swarm — the 600s watchdog stall, filesystem contention with 5+ agents, load-bearing false premises in the BRIEF. Each one with the fix.',
      '3 ScreenshotPlaceholder slots — tmux running multi-agent dispatch, /swarm-strategic-plan output folder, /agent-wave-verify catching a stub. Placeholders mark intent; screenshots get captured live.',
      'Ch 06 callout — added a tip box at the top of "The Swarm" chapter pointing to /swarms as the deep reference (chapter = story, page = playbook)',
      'Ch 40 cross-link upgraded — the "swarms tease" section in Ch 40 now links to /swarms (was text-only when /swarms didn\'t exist yet)',
      'Cmd-K — /swarms page entry + 10 section anchors searchable',
    ],
    receipts: [
      { label: 'New page', value: '/swarms · ~3,800 words · 10 sections · reuses SwarmVisualizer' },
      { label: 'Skills documented', value: '10 (with paths in ~/.claude/skills/)' },
      { label: 'Swarm patterns codified', value: '7 (each with a failure-receipt origin)' },
      { label: 'Orchestration prompts published', value: '3 (dispatch envelope, /audit shape, BRIEF template)' },
    ],
  },
  {
    edition: 'Edition 9',
    date: '2026-05-20',
    tagline: 'Prompting is basic now. The leverage moved up the ladder.',
    shipped: [
      'New Chapter 40 — "Prompting, or the Knob You Probably Shouldn\'t Tune" (~3,200 words, 12-min read). The contrarian take: prompting is a basic skill now, the real ladder is skills → swarms → memory → data layer. Opens with the verbatim "rigor enforcer" prompt (works, but the wrong leverage) and contrasts it side-by-side with PROMPT_EOD from /resources (the operator-grade shape). Closes with a Monday move: pick the prompt you\'ve tweaked 5+ times and promote it to a skill, schedule, or swarm.',
      'New page /github-playbook — "GitHub for non-developers" (~3,400 words). GH-is-the-new-LinkedIn reframe, 5 non-code uses (private repo as delivery surface, README as living doc, Issues as ops queue, Discussions as forum, Releases as launch posts), the 8 gh commands you actually need, what you can safely ignore (branches, rebasing, merge conflicts, 80% of git), six examples in the wild (Vlad\'s Playbook + AFC + Karpathy/nanoGPT + Simon Willison/TIL + Willison/blog source + GitHub profile README pattern), and the Saturday move.',
      'Ch 40 placed in Part II (Working Memory) — sits next to the vault, skills, build-a-skill, and connectors-MCP chapters. Also added to SECTIONS "claude" topical group.',
      'Cmd-K wired — Ch 40 chapter entry + synonyms (prompting, prompt engineering, chain of thought, ladder, rigor enforcer, etc.), /github-playbook page entry + 8 section anchors searchable',
      'Ch 19 cross-link callout — added a tip box near the gh repo create snippet pointing non-developers to /github-playbook',
      'Fact-checked: nanoGPT marked deprecated by Karpathy in Nov 2025 (still live; example notes the move to nanochat). Originally proposed Patrick Collison reading-list example swapped for Simon Willison blog source (Collison\'s reading list is NOT on GitHub — fact-verified). Anthropic prompting docs URL host updated (docs.anthropic.com → platform.claude.com).',
    ],
    receipts: [
      { label: 'New chapter', value: 'Ch 40 · 40-prompting-knob · Part II · ~3,200 words' },
      { label: 'New page', value: '/github-playbook · 6 examples · 8 gh commands · ~3,400 words' },
      { label: 'Slop catches by research agent', value: '3 (Collison/nanoGPT/gh-pages-flag — all corrected before push)' },
      { label: 'Cross-links wired', value: 'Ch 19 → /github-playbook, Ch 40 → Ch 04/05/06/12/37, /github-playbook → /html-first + /sovereign-stack' },
    ],
  },
  {
    edition: 'Edition 8.2',
    date: '2026-05-20',
    tagline: 'HTML-ization, expanded — the recipe, the gallery, the receipts, the edges.',
    shipped: [
      '/html-first expanded from 4 sections to 9: kept the existing case (AFC + Folderly audit + Do-this-Monday) and added five new ones',
      'New section "More across the portfolio" — the order of operations (pitches first, audits next, internal deliverables third, communication fourth), the one-to-two gap that flips the format from curiosity to default, the Playbook itself as the maximal version of the thesis',
      'New section "The recipe — do this Saturday" — exact verbatim prompt template (12-line constraint block), the four-step ladder (shape → prompt → three iterations → deploy), and the gh-create-repo deploy snippet',
      'New section "Applications gallery" — 12 deliverable shapes that work (audit, pitch, QBR, board, mentee tracker, weekly KPI, financial model, brief, strategy memo, newsletter, conference companion, retro) rendered as a 3-col grid',
      'New section "Not for everything — where this fails" — four honest edges where htmlization should not be used (legal documents, e-signatures, link-averse readers, deploy overhead vs reward)',
      'New section "The pattern in the wild" — 12 public examples sourced (Ciechanowski Moon, Stripe Annual Letter, AI 2027, Anthropic attribution graphs, NYT needle, Ramp benchmarks, a16z market map, Pudding, Bloomberg year-in-graphics, Linear changelog, OWID, Nicky Case) rendered as a clickable 3-col grid with deep links, plus four emerging-pattern paragraphs',
      'SectionNav updated 4 items → 9 items; Cmd-K HTMLFIRST_SECTIONS updated to match for discoverability',
    ],
    receipts: [
      { label: 'Page sections', value: '4 → 9 (+5)' },
      { label: 'New gallery cards (operator applications)', value: '12 shapes' },
      { label: 'New "in the wild" citations', value: '12 sourced public examples, 2024–2026' },
      { label: 'New page weight', value: '+5,500 words approx · still single page, no nav split' },
    ],
  },
  {
    edition: 'Edition 8.1',
    date: '2026-05-20',
    tagline: 'The launch as its own experiment in the thesis.',
    shipped: [
      'New /launch-week page — the launch is its own forwardable artifact. Numbers panel (live GitHub stars, newsletter open rate, subs delta, page-views), a day-by-day timeline of every distribution surface, a "what I\'d do differently" section that populates from real data not Day-0 guesses, a meta-callout explaining why a PDF version would be obsolete the second it was exported',
      'src/lib/launch-week.ts — single source of truth for the timeline + numbers + retrospective; append-only daily edits (one-line additions, no schema breaking)',
      'Day-0 distribution drafts authored locally (notes/launch/, gitignored): 8-tweet X thread (each tweet stands alone), LinkedIn longform (founder-realization frame), Hacker News Show HN (title + first-comment), Day-7 Numbers newsletter template with TBD slots',
      'Homepage tile grid restored to 4-up across multiple rows — 8 tiles: Sovereign Stack · HTML-ization · The launch · Launch week · Vault library · Cheat sheet · Glossary · Tier list. About moved to the small text-link below.',
      'Cmd-K indexes /launch-week as a discoverable destination',
    ],
    receipts: [
      { label: 'New page', value: '/launch-week' },
      { label: 'Distribution surfaces drafted', value: '4 (Newsletter · X · LinkedIn · HN)' },
      { label: 'Homepage tiles', value: '4 → 8 (2 rows of 4)' },
      { label: 'Day-7 follow-up scheduled', value: 'Numbers post — receipts of launch week, sent regardless of how it goes' },
    ],
  },
  {
    edition: 'Edition 8',
    date: '2026-05-20',
    tagline: 'Two stacks, not one. The sovereign tier is built.',
    shipped: [
      'New /sovereign-stack page — the open-weights answer to the deprecation calendar. The Onyx Open-Source LLM Leaderboard rebuilt as a tier list (Overall / Coding / Math / Chat / Reasoning), Ollama vs LM Studio vs vLLM, five hardware tiers ($2k MacBook → $40k+ deploy) with what-breaks-first per tier, quantization + KV-cache math, open-vs-closed cost-per-task table (30× ratio on repeated evals), the heretic question (abliteration framed as sovereignty, not jailbreaking), the Mythos lesson, Karpathy nano-gpt as a Saturday curriculum, the 6-month watch list',
      'New OnyxLeaderboard.tsx widget — interactive S/A/B/C/D tier list with category tabs, size filters (Small/Medium/Large by parameter count), and per-lab filters showing the Chinese-lab dominance of the open-weights frontier (6/6 S-tier slots)',
      'New glossary terms — Sovereign stack · Heretic model · Mythos · Abliteration — all cross-linked',
      'Ch 24 (tier-list) callout pointing to /sovereign-stack — the closed-model tier list and the open-weights tier list now talk to each other',
      'Homepage tile grid rebalanced — Sovereign Stack takes flagship-first position (4 across), Glossary + tier-list + launch + about demoted to a single text row of secondary links below the grid',
    ],
    receipts: [
      { label: 'New page', value: '/sovereign-stack' },
      { label: 'Leaderboard snapshot', value: 'Onyx Open-Source LLM Leaderboard · 2026-03-24 · 19 models across 5 categories' },
      { label: 'Sourced citations', value: '60+ inline links — Arditi 2024, modded-nanogpt, Onyx, Ollama MLX, all model releases' },
      { label: 'Open-weights S-tier (May 2026)', value: 'GLM-5 · Kimi K2.5 · MiniMax M2.5 · DeepSeek V3.2 · Step-3.5-Flash · Qwen 3.5' },
    ],
  },
  {
    edition: 'Edition 7',
    date: '2026-05-20',
    tagline: 'The book is open. The source is the recipe.',
    shipped: [
      'Repo flipped to public after a full git-filter-repo history scrub — 71 commits rewritten, 0 leaks across blobs and commit messages from an independent fresh-clone verification, backup ref preserved server-side',
      'New /launch page — the launch artifact IS the demo: typewriter hero, animated stat odometer (chapters/widgets/glossary/embeds/editions/stars), the 3 live embedded case studies, all 39 chapters as a click-anywhere mosaic, what-it-took timeline, post-credit AFC tease',
      'Homepage "Now" banner above the tile grid promoting the launch through launch week',
      'README rewrite to current reality (Edition 6/7, real counts, dive.vladyslavpodoliako.com as primary CTA), repo metadata (description, homepage, 12 topics, Discussions on), custom 1280x640 GitHub social-preview image',
      'SECURITY.md + CONTRIBUTING.md refreshed for the public posture; private-vulnerability-reporting path documented',
      'Ch 02 contradiction fixed (the Fathom-in-the-don\'t-use-bin error caught externally) — reframed as "picked Fathom, killed the rest" with the discipline of one transcript surface',
    ],
    receipts: [
      { label: 'Repo state', value: 'PUBLIC · github.com/Belkins/ai-dive-deep' },
      { label: 'History leaks (post-scrub, fresh-clone verified)', value: '0 / 71 commits' },
      { label: 'New page', value: '/launch' },
      { label: 'Edition 1 → public', value: '13 days, 7 editions' },
    ],
  },
  {
    edition: 'Edition 6',
    date: '2026-05-19',
    tagline: 'The method, embedded. Click the artifacts.',
    shipped: [
      'New /html-first page — the htmlization thesis (every deliverable ships as a live interactive artifact, not a dead file) with two REAL artifacts embedded and clickable',
      'AFC case: the dinner-table idea whose investment deck + robot-stable annex got spun up as interactive HTML before the next meeting — Vlad\'s own venture, embedded as-is',
      'Folderly case: a real ~90-domain / ~5K-mailbox external deliverability audit, swarm-produced on the Folderly methodology — fully de-identified (client, all 90 domains, SPF/infra fingerprints, WHOIS name) and embedded as a sanitized sample',
      'New ArtifactEmbed.astro — sandboxed, lazy, render-on-click iframe modal (no src until opened; referrerpolicy=no-referrer)',
      'Ch 19 callout + glossary "Htmlization" + Cmd-K (page + 4 section anchors) wired',
    ],
    receipts: [
      { label: 'Live artifacts embedded', value: '3 (AFC ×2, audit ×1)' },
      { label: 'Folderly identifiers redacted', value: '90 domains + name + 2 SPF + WHOIS → 0 residual' },
      { label: 'New page / component', value: '/html-first + ArtifactEmbed' },
      { label: 'External calls in embeds', value: '0 (fully self-contained)' },
    ],
  },
  {
    edition: 'Edition 5',
    date: '2026-05-19',
    tagline: 'The bench moved. The reports stopped being files.',
    shipped: [
      'Gemini 3.5 Flash + Claude-for-the-legal-industry logged as dated research notes — signal-vs-receipt discipline, not a leaderboard edit',
      'Ch 35: corrected the stale "Gemini 3 Pro" reference + added the Flash-beats-last-gen-Pro signal, scoped as a Ch 29 cost question rather than a re-tiering',
      'Ch 29: new section — "The price of a model is not the price of a task" + a cost-per-task test loop you run on your own traffic',
      'Ch 24: May-2026 addendum extended; the live LMArena widget stays the source of truth — no slide-driven tier edits',
      'New thesis across Ch 19 / Ch 26 / About — every report ships as a living link on a private repo, not a dead file; unsanctioned copying as the truest adoption metric',
    ],
    receipts: [
      { label: 'Research notes added', value: '2' },
      { label: 'Chapters touched', value: '19, 24, 26, 29, 35' },
      { label: 'Live bench edits', value: '0 (signal, not receipt)' },
      { label: 'New components', value: '0' },
    ],
  },
  {
    edition: 'Edition 4',
    date: '2026-05-11',
    tagline: 'Retitled for navigation. Voice survived.',
    shipped: [
      'All 36 chapter titles rewritten — topical-primary, with question form on 9 chapters where intent shape beats subject shape',
      'Old hype titles preserved as subtitles ("The Day I Killed My Tabs" now sits below "AI as an Operating System")',
      'Cmd-K resolves "cron" → Scheduled Tasks, "browser" → Browser Agents with Playwright, "permissions" → When to Skip Permissions',
      'scripts/apply-titles.py — atomic re-runnable rewrite of all 36 frontmatters + chapters.ts. Re-run any time the map changes.',
    ],
    receipts: [
      { label: 'Chapters retitled', value: '36' },
      { label: 'Time to scan TOC', value: '~6s → ~2s' },
      { label: 'Voice lines lost', value: '0' },
    ],
  },
  {
    edition: 'Edition 3.5',
    date: '2026-05-09',
    tagline: "Repo flipped private. Site stayed public.",
    shipped: [
      'Repo visibility flipped to PRIVATE (Belkins on GH Pro tier)',
      'Issues, Wiki, Projects, Discussions disabled — attack surface reduced',
      'SECURITY.md committed with vulnerability reporting + ops rules',
      '.gitignore hardened — .pem, .key, .aws/, .kube/, secrets/, .vercel',
      'Vercel fallback config committed — dual-target astro.config.mjs reads DEPLOY_TARGET env',
      'Vercel security headers baked (HSTS, X-Frame-Options DENY, X-Content-Type-Options, Permissions-Policy)',
    ],
    receipts: [
      { label: 'Repo visibility', value: 'PUBLIC → PRIVATE' },
      { label: 'Site downtime during flip', value: '~3 min (Pages re-enable required)' },
      { label: 'Surfaces disabled', value: '4' },
    ],
  },
  {
    edition: 'Edition 3',
    date: '2026-05-07',
    tagline: 'Closed the original brief. Six new chapters, two new pages.',
    shipped: [
      'Ch 31 — The Stages: Ideation → Foundation → Creation → Polishing → Security → Deploy',
      'Ch 32 — How to Build Rick (OpenClaw, NemoClaw, Hermes archetypes)',
      'Ch 33 — Browser Agents with Playwright (login, click, scrape, post)',
      'Ch 34 — Persona Agents and the Four NEVERs',
      'Ch 35 — Codex × Claude Code (day shift, night shift)',
      'Ch 36 — Beyond Claude Code (CrewAI, LangGraph, SDK)',
      'StagesFlow widget (Ch 31) — six clickable stages with artifact + ready test + failure mode',
      'ArchetypePicker widget (Ch 32) — 3-question intake → recommended Rick archetype + install command',
      '/day-zero — literal first 30 minutes with 12 localStorage-persisted checkboxes',
      '/sections — chapters grouped by General / Claude / Security / AI Agents / Building / Team+Tier',
    ],
    receipts: [
      { label: 'Chapters added', value: '+6 (30 → 36)' },
      { label: 'Widgets added', value: '+2 (12 → 14)' },
      { label: 'New pages', value: '+2 (/day-zero, /sections)' },
    ],
  },
  {
    edition: 'Storytelling layer',
    date: '2026-05-08',
    tagline: '36 islands became one six-act journey.',
    shipped: [
      '/how-to-read — ~1,100-word prologue. Who this is for, the reframe, the journey, three ways to use the book.',
      '/journey — 6-part narrative arc (Reframe → Memory → Workshop → Discipline → Building → Frontier)',
      '/questions — 18 questions Vlad answers most weeks, each with short answer + chapter pointers',
      'Part pill on every chapter hero — readers know where they are in the arc',
      'Chapter footer transitions detect part boundaries: "Next: Part III — The Workshop →"',
      '/showcase — auto-extracted from ~/.claude/: 62 skills + 32 custom agents + 12 plugins, categorized + searchable',
      '/cowork-setup — sanitized: 12 connector categories + 8 scheduled-task patterns + day-shape timeline. Zero local-data scan.',
    ],
    receipts: [
      { label: 'Reader-facing pages added', value: '+5' },
      { label: 'Skills surfaced', value: '62' },
      { label: 'Sensitive paths read', value: '0 (Cowork showcase derived from published chapters)' },
    ],
  },
  {
    edition: 'Edition 2',
    date: '2026-05-07',
    tagline: 'Fixed the muscles. Wrote the spine.',
    shipped: [
      '6 new chapters (Ch 25-30): Evals, Team Adoption, Voice Agents, Failure Receipts, Cost Economics, Anthropic SDK Direct',
      '4 new widgets: TokenBurnCalculator (Ch 2/29), TempAgencyLoop (Ch 3), VaultGraphPreview (Ch 4), HookEventTimeline (Ch 16)',
      '12 a11y + UX patches: glossary popovers via Radix (no more navigate-away mid-read), focus rings, skip-to-content, paper contrast fix, 17px body on ≥640px, anchor links on H2/H3, print stylesheet',
      '10 new operator prompts added to /resources: deal post-mortem, hire screen, model migration, board update, mentee prep, RFP triage, kill decision, customer-call synthesis, writing-filter, Tuesday-9am triage',
      'ResumeReading pill on landing (localStorage-driven)',
      'Substack subscribe iframe in footer',
      'Sharper "Most readers go here next" copy in chapter footer',
    ],
    receipts: [
      { label: 'Chapters', value: '24 → 30' },
      { label: 'Widgets', value: '8 → 12' },
      { label: 'Pages', value: '32 → 38' },
    ],
  },
  {
    edition: 'Edition 1',
    date: '2026-05-07',
    tagline: 'The book became an artifact.',
    shipped: [
      '24 chapters migrated from .docx into MDX (4 parallel agents, partitioned by chapter range)',
      '8 interactive widgets: StackSelector, SwarmVisualizer, CronBuilder, ModePicker, SkillComposer, ConnectorMap, PermissionSimulator, TierListBuilder',
      'Cmd-K command palette + dark theme + view transitions + reading progress bar',
      'Resources page with copy-paste vault library: CLAUDE.md skeleton, .mcp.json examples, hook scripts, SKILL templates, 5 reusable prompts',
      'Printable cheat sheet (Ch 14, @media print styled)',
      '30-day plan generator (3 intake questions → custom 30-day calendar, .ics + markdown export)',
      'Drag-and-drop tier list builder with shareable URL hash',
      'GitHub Pages deployment via Actions; live in ~50s per push',
    ],
    receipts: [
      { label: 'Source words migrated', value: '~43,000' },
      { label: 'Parallel agents in chapter migration', value: '4' },
      { label: 'Wall-clock for full Edition 1 build', value: '~3 hours' },
      { label: 'Dist size', value: '1.4 MB / 32 pages' },
    ],
  },
];
