// Edition timeline. Update when shipping a new edition.

export type ChangelogEntry = {
  edition: string;
  date: string;        // ISO yyyy-mm-dd
  tagline: string;
  shipped: string[];
  receipts?: { label: string; value: string }[];
};

export const CHANGELOG: ChangelogEntry[] = [
  {
    edition: 'Edition 9.1',
    date: '2026-05-20',
    tagline: 'Swarms — the deep version, with the skills and the prompts and the receipts.',
    shipped: [
      'New /swarms page (~3,800 words) — the operator\'s deep dive into multi-agent orchestration. Embeds the SwarmVisualizer widget (4 patterns animated: fan-out, pipeline, map-reduce, adversarial). The 5 × 4 wave pattern explained with the real five-wave breakdown from /swarm-strategic-plan.',
      'The skill shelf — 10 swarm skills listed with shape + use case + file path: /swarm-strategic-plan, /debug-swarm, /audit, /agent-wave-verify, /folderly-external-audit, /cross-trio-audit, /bughunter, /ultrareview, /gstack-qa, /gstack-review',
      'Seven swarm patterns from memory — CANON-lock + red-team / design-variant / perspectival editorial / multi-model bake-off / script-not-swarm collector / data-injection-slot / demand-test ≠ build. Each one earned its place by failing first; each gets one paragraph with the receipt.',
      'Three orchestration prompts to steal — the universal subagent dispatch envelope (with the inline-fallback contract), the /audit 6-agent parallel dispatch shape, the BRIEF.md template with HARD CONSTRAINTS section that load-bears across 20 agents',
      'Three things that quietly break a swarm — the 600s watchdog stall, filesystem contention with 5+ agents, load-bearing false premises in the BRIEF. Each one with the fix.',
      '3 ScreenshotPlaceholder slots — tmux running multi-agent dispatch, /swarm-strategic-plan output folder, /agent-wave-verify catching a stub. Placeholders mark intent; screenshots get captured live.',
      'Ch 06 callout — added a tip box at the top of "The Swarm" chapter pointing to /swarms as the deep reference (chapter = story, page = playbook)',
      'Ch 40 cross-link upgraded — the "swarms tease" section in Ch 40 now links to /swarms (was text-only when /swarms didn\'t exist yet)',
      'Cmd-K — /swarms page entry + 10 section anchors searchable',
    ],
    receipts: [
      { label: 'New page', value: '/swarms · ~3,800 words · 10 sections · reuses SwarmVisualizer' },
      { label: 'Skills documented', value: '10 (with paths in ~/.claude/skills/)' },
      { label: 'Swarm patterns codified', value: '7 (each with a failure-receipt origin)' },
      { label: 'Orchestration prompts published', value: '3 (dispatch envelope, /audit shape, BRIEF template)' },
    ],
  },
  {
    edition: 'Edition 9',
    date: '2026-05-20',
    tagline: 'Prompting is basic now. The leverage moved up the ladder.',
    shipped: [
      'New Chapter 40 — "Prompting, or the Knob You Probably Shouldn\'t Tune" (~3,200 words, 12-min read). The contrarian take: prompting is a basic skill now, the real ladder is skills → swarms → memory → data layer. Opens with the verbatim "rigor enforcer" prompt (works, but the wrong leverage) and contrasts it side-by-side with PROMPT_EOD from /resources (the operator-grade shape). Closes with a Monday move: pick the prompt you\'ve tweaked 5+ times and promote it to a skill, schedule, or swarm.',
      'New page /github-playbook — "GitHub for non-developers" (~3,400 words). GH-is-the-new-LinkedIn reframe, 5 non-code uses (private repo as delivery surface, README as living doc, Issues as ops queue, Discussions as forum, Releases as launch posts), the 8 gh commands you actually need, what you can safely ignore (branches, rebasing, merge conflicts, 80% of git), six examples in the wild (Vlad\'s Playbook + AFC + Karpathy/nanoGPT + Simon Willison/TIL + Willison/blog source + GitHub profile README pattern), and the Saturday move.',
      'Ch 40 placed in Part II (Working Memory) — sits next to the vault, skills, build-a-skill, and connectors-MCP chapters. Also added to SECTIONS "claude" topical group.',
      'Cmd-K wired — Ch 40 chapter entry + synonyms (prompting, prompt engineering, chain of thought, ladder, rigor enforcer, etc.), /github-playbook page entry + 8 section anchors searchable',
      'Ch 19 cross-link callout — added a tip box near the gh repo create snippet pointing non-developers to /github-playbook',
      'Fact-checked: nanoGPT marked deprecated by Karpathy in Nov 2025 (still live; example notes the move to nanochat). Originally proposed Patrick Collison reading-list example swapped for Simon Willison blog source (Collison\'s reading list is NOT on GitHub — fact-verified). Anthropic prompting docs URL host updated (docs.anthropic.com → platform.claude.com).',
    ],
    receipts: [
      { label: 'New chapter', value: 'Ch 40 · 40-prompting-knob · Part II · ~3,200 words' },
      { label: 'New page', value: '/github-playbook · 6 examples · 8 gh commands · ~3,400 words' },
      { label: 'Slop catches by research agent', value: '3 (Collison/nanoGPT/gh-pages-flag — all corrected before push)' },
      { label: 'Cross-links wired', value: 'Ch 19 → /github-playbook, Ch 40 → Ch 04/05/06/12/37, /github-playbook → /html-first + /sovereign-stack' },
    ],
  },
  {
    edition: 'Edition 8.2',
    date: '2026-05-20',
    tagline: 'HTML-ization, expanded — the recipe, the gallery, the receipts, the edges.',
    shipped: [
      '/html-first expanded from 4 sections to 9: kept the existing case (AFC + Folderly audit + Do-this-Monday) and added five new ones',
      'New section "More across the portfolio" — the order of operations (pitches first, audits next, internal deliverables third, communication fourth), the one-to-two gap that flips the format from curiosity to default, the Playbook itself as the maximal version of the thesis',
      'New section "The recipe — do this Saturday" — exact verbatim prompt template (12-line constraint block), the four-step ladder (shape → prompt → three iterations → deploy), and the gh-create-repo deploy snippet',
      'New section "Applications gallery" — 12 deliverable shapes that work (audit, pitch, QBR, board, mentee tracker, weekly KPI, financial model, brief, strategy memo, newsletter, conference companion, retro) rendered as a 3-col grid',
      'New section "Not for everything — where this fails" — four honest edges where htmlization should not be used (legal documents, e-signatures, link-averse readers, deploy overhead vs reward)',
      'New section "The pattern in the wild" — 12 public examples sourced (Ciechanowski Moon, Stripe Annual Letter, AI 2027, Anthropic attribution graphs, NYT needle, Ramp benchmarks, a16z market map, Pudding, Bloomberg year-in-graphics, Linear changelog, OWID, Nicky Case) rendered as a clickable 3-col grid with deep links, plus four emerging-pattern paragraphs',
      'SectionNav updated 4 items → 9 items; Cmd-K HTMLFIRST_SECTIONS updated to match for discoverability',
    ],
    receipts: [
      { label: 'Page sections', value: '4 → 9 (+5)' },
      { label: 'New gallery cards (operator applications)', value: '12 shapes' },
      { label: 'New "in the wild" citations', value: '12 sourced public examples, 2024–2026' },
      { label: 'New page weight', value: '+5,500 words approx · still single page, no nav split' },
    ],
  },
  {
    edition: 'Edition 8.1',
    date: '2026-05-20',
    tagline: 'The launch as its own experiment in the thesis.',
    shipped: [
      'New /launch-week page — the launch is its own forwardable artifact. Numbers panel (live GitHub stars, newsletter open rate, subs delta, page-views), a day-by-day timeline of every distribution surface, a "what I\'d do differently" section that populates from real data not Day-0 guesses, a meta-callout explaining why a PDF version would be obsolete the second it was exported',
      'src/lib/launch-week.ts — single source of truth for the timeline + numbers + retrospective; append-only daily edits (one-line additions, no schema breaking)',
      'Day-0 distribution drafts authored locally (notes/launch/, gitignored): 8-tweet X thread (each tweet stands alone), LinkedIn longform (founder-realization frame), Hacker News Show HN (title + first-comment), Day-7 Numbers newsletter template with TBD slots',
      'Homepage tile grid restored to 4-up across multiple rows — 8 tiles: Sovereign Stack · HTML-ization · The launch · Launch week · Vault library · Cheat sheet · Glossary · Tier list. About moved to the small text-link below.',
      'Cmd-K indexes /launch-week as a discoverable destination',
    ],
    receipts: [
      { label: 'New page', value: '/launch-week' },
      { label: 'Distribution surfaces drafted', value: '4 (Newsletter · X · LinkedIn · HN)' },
      { label: 'Homepage tiles', value: '4 → 8 (2 rows of 4)' },
      { label: 'Day-7 follow-up scheduled', value: 'Numbers post — receipts of launch week, sent regardless of how it goes' },
    ],
  },
  {
    edition: 'Edition 8',
    date: '2026-05-20',
    tagline: 'Two stacks, not one. The sovereign tier is built.',
    shipped: [
      'New /sovereign-stack page — the open-weights answer to the deprecation calendar. The Onyx Open-Source LLM Leaderboard rebuilt as a tier list (Overall / Coding / Math / Chat / Reasoning), Ollama vs LM Studio vs vLLM, five hardware tiers ($2k MacBook → $40k+ deploy) with what-breaks-first per tier, quantization + KV-cache math, open-vs-closed cost-per-task table (30× ratio on repeated evals), the heretic question (abliteration framed as sovereignty, not jailbreaking), the Mythos lesson, Karpathy nano-gpt as a Saturday curriculum, the 6-month watch list',
      'New OnyxLeaderboard.tsx widget — interactive S/A/B/C/D tier list with category tabs, size filters (Small/Medium/Large by parameter count), and per-lab filters showing the Chinese-lab dominance of the open-weights frontier (6/6 S-tier slots)',
      'New glossary terms — Sovereign stack · Heretic model · Mythos · Abliteration — all cross-linked',
      'Ch 24 (tier-list) callout pointing to /sovereign-stack — the closed-model tier list and the open-weights tier list now talk to each other',
      'Homepage tile grid rebalanced — Sovereign Stack takes flagship-first position (4 across), Glossary + tier-list + launch + about demoted to a single text row of secondary links below the grid',
    ],
    receipts: [
      { label: 'New page', value: '/sovereign-stack' },
      { label: 'Leaderboard snapshot', value: 'Onyx Open-Source LLM Leaderboard · 2026-03-24 · 19 models across 5 categories' },
      { label: 'Sourced citations', value: '60+ inline links — Arditi 2024, modded-nanogpt, Onyx, Ollama MLX, all model releases' },
      { label: 'Open-weights S-tier (May 2026)', value: 'GLM-5 · Kimi K2.5 · MiniMax M2.5 · DeepSeek V3.2 · Step-3.5-Flash · Qwen 3.5' },
    ],
  },
  {
    edition: 'Edition 7',
    date: '2026-05-20',
    tagline: 'The book is open. The source is the recipe.',
    shipped: [
      'Repo flipped to public after a full git-filter-repo history scrub — 71 commits rewritten, 0 leaks across blobs and commit messages from an independent fresh-clone verification, backup ref preserved server-side',
      'New /launch page — the launch artifact IS the demo: typewriter hero, animated stat odometer (chapters/widgets/glossary/embeds/editions/stars), the 3 live embedded case studies, all 39 chapters as a click-anywhere mosaic, what-it-took timeline, post-credit AFC tease',
      'Homepage "Now" banner above the tile grid promoting the launch through launch week',
      'README rewrite to current reality (Edition 6/7, real counts, dive.vladyslavpodoliako.com as primary CTA), repo metadata (description, homepage, 12 topics, Discussions on), custom 1280x640 GitHub social-preview image',
      'SECURITY.md + CONTRIBUTING.md refreshed for the public posture; private-vulnerability-reporting path documented',
      'Ch 02 contradiction fixed (the Fathom-in-the-don\'t-use-bin error caught externally) — reframed as "picked Fathom, killed the rest" with the discipline of one transcript surface',
    ],
    receipts: [
      { label: 'Repo state', value: 'PUBLIC · github.com/Belkins/ai-dive-deep' },
      { label: 'History leaks (post-scrub, fresh-clone verified)', value: '0 / 71 commits' },
      { label: 'New page', value: '/launch' },
      { label: 'Edition 1 → public', value: '13 days, 7 editions' },
    ],
  },
  {
    edition: 'Edition 6',
    date: '2026-05-19',
    tagline: 'The method, embedded. Click the artifacts.',
    shipped: [
      'New /html-first page — the htmlization thesis (every deliverable ships as a live interactive artifact, not a dead file) with two REAL artifacts embedded and clickable',
      'AFC case: the dinner-table idea whose investment deck + robot-stable annex got spun up as interactive HTML before the next meeting — Vlad\'s own venture, embedded as-is',
      'Folderly case: a real ~90-domain / ~5K-mailbox external deliverability audit, swarm-produced on the Folderly methodology — fully de-identified (client, all 90 domains, SPF/infra fingerprints, WHOIS name) and embedded as a sanitized sample',
      'New ArtifactEmbed.astro — sandboxed, lazy, render-on-click iframe modal (no src until opened; referrerpolicy=no-referrer)',
      'Ch 19 callout + glossary "Htmlization" + Cmd-K (page + 4 section anchors) wired',
    ],
    receipts: [
      { label: 'Live artifacts embedded', value: '3 (AFC ×2, audit ×1)' },
      { label: 'Folderly identifiers redacted', value: '90 domains + name + 2 SPF + WHOIS → 0 residual' },
      { label: 'New page / component', value: '/html-first + ArtifactEmbed' },
      { label: 'External calls in embeds', value: '0 (fully self-contained)' },
    ],
  },
  {
    edition: 'Edition 5',
    date: '2026-05-19',
    tagline: 'The bench moved. The reports stopped being files.',
    shipped: [
      'Gemini 3.5 Flash + Claude-for-the-legal-industry logged as dated research notes — signal-vs-receipt discipline, not a leaderboard edit',
      'Ch 35: corrected the stale "Gemini 3 Pro" reference + added the Flash-beats-last-gen-Pro signal, scoped as a Ch 29 cost question rather than a re-tiering',
      'Ch 29: new section — "The price of a model is not the price of a task" + a cost-per-task test loop you run on your own traffic',
      'Ch 24: May-2026 addendum extended; the live LMArena widget stays the source of truth — no slide-driven tier edits',
      'New thesis across Ch 19 / Ch 26 / About — every report ships as a living link on a private repo, not a dead file; unsanctioned copying as the truest adoption metric',
    ],
    receipts: [
      { label: 'Research notes added', value: '2' },
      { label: 'Chapters touched', value: '19, 24, 26, 29, 35' },
      { label: 'Live bench edits', value: '0 (signal, not receipt)' },
      { label: 'New components', value: '0' },
    ],
  },
  {
    edition: 'Edition 4',
    date: '2026-05-11',
    tagline: 'Retitled for navigation. Voice survived.',
    shipped: [
      'All 36 chapter titles rewritten — topical-primary, with question form on 9 chapters where intent shape beats subject shape',
      'Old hype titles preserved as subtitles ("The Day I Killed My Tabs" now sits below "AI as an Operating System")',
      'Cmd-K resolves "cron" → Scheduled Tasks, "browser" → Browser Agents with Playwright, "permissions" → When to Skip Permissions',
      'scripts/apply-titles.py — atomic re-runnable rewrite of all 36 frontmatters + chapters.ts. Re-run any time the map changes.',
    ],
    receipts: [
      { label: 'Chapters retitled', value: '36' },
      { label: 'Time to scan TOC', value: '~6s → ~2s' },
      { label: 'Voice lines lost', value: '0' },
    ],
  },
  {
    edition: 'Edition 3.5',
    date: '2026-05-09',
    tagline: "Repo flipped private. Site stayed public.",
    shipped: [
      'Repo visibility flipped to PRIVATE (Belkins on GH Pro tier)',
      'Issues, Wiki, Projects, Discussions disabled — attack surface reduced',
      'SECURITY.md committed with vulnerability reporting + ops rules',
      '.gitignore hardened — .pem, .key, .aws/, .kube/, secrets/, .vercel',
      'Vercel fallback config committed — dual-target astro.config.mjs reads DEPLOY_TARGET env',
      'Vercel security headers baked (HSTS, X-Frame-Options DENY, X-Content-Type-Options, Permissions-Policy)',
    ],
    receipts: [
      { label: 'Repo visibility', value: 'PUBLIC → PRIVATE' },
      { label: 'Site downtime during flip', value: '~3 min (Pages re-enable required)' },
      { label: 'Surfaces disabled', value: '4' },
    ],
  },
  {
    edition: 'Edition 3',
    date: '2026-05-07',
    tagline: 'Closed the original brief. Six new chapters, two new pages.',
    shipped: [
      'Ch 31 — The Stages: Ideation → Foundation → Creation → Polishing → Security → Deploy',
      'Ch 32 — How to Build Rick (OpenClaw, NemoClaw, Hermes archetypes)',
      'Ch 33 — Browser Agents with Playwright (login, click, scrape, post)',
      'Ch 34 — Persona Agents and the Four NEVERs',
      'Ch 35 — Codex × Claude Code (day shift, night shift)',
      'Ch 36 — Beyond Claude Code (CrewAI, LangGraph, SDK)',
      'StagesFlow widget (Ch 31) — six clickable stages with artifact + ready test + failure mode',
      'ArchetypePicker widget (Ch 32) — 3-question intake → recommended Rick archetype + install command',
      '/day-zero — literal first 30 minutes with 12 localStorage-persisted checkboxes',
      '/sections — chapters grouped by General / Claude / Security / AI Agents / Building / Team+Tier',
    ],
    receipts: [
      { label: 'Chapters added', value: '+6 (30 → 36)' },
      { label: 'Widgets added', value: '+2 (12 → 14)' },
      { label: 'New pages', value: '+2 (/day-zero, /sections)' },
    ],
  },
  {
    edition: 'Storytelling layer',
    date: '2026-05-08',
    tagline: '36 islands became one six-act journey.',
    shipped: [
      '/how-to-read — ~1,100-word prologue. Who this is for, the reframe, the journey, three ways to use the book.',
      '/journey — 6-part narrative arc (Reframe → Memory → Workshop → Discipline → Building → Frontier)',
      '/questions — 18 questions Vlad answers most weeks, each with short answer + chapter pointers',
      'Part pill on every chapter hero — readers know where they are in the arc',
      'Chapter footer transitions detect part boundaries: "Next: Part III — The Workshop →"',
      '/showcase — auto-extracted from ~/.claude/: 62 skills + 32 custom agents + 12 plugins, categorized + searchable',
      '/cowork-setup — sanitized: 12 connector categories + 8 scheduled-task patterns + day-shape timeline. Zero local-data scan.',
    ],
    receipts: [
      { label: 'Reader-facing pages added', value: '+5' },
      { label: 'Skills surfaced', value: '62' },
      { label: 'Sensitive paths read', value: '0 (Cowork showcase derived from published chapters)' },
    ],
  },
  {
    edition: 'Edition 2',
    date: '2026-05-07',
    tagline: 'Fixed the muscles. Wrote the spine.',
    shipped: [
      '6 new chapters (Ch 25-30): Evals, Team Adoption, Voice Agents, Failure Receipts, Cost Economics, Anthropic SDK Direct',
      '4 new widgets: TokenBurnCalculator (Ch 2/29), TempAgencyLoop (Ch 3), VaultGraphPreview (Ch 4), HookEventTimeline (Ch 16)',
      '12 a11y + UX patches: glossary popovers via Radix (no more navigate-away mid-read), focus rings, skip-to-content, paper contrast fix, 17px body on ≥640px, anchor links on H2/H3, print stylesheet',
      '10 new operator prompts added to /resources: deal post-mortem, hire screen, model migration, board update, mentee prep, RFP triage, kill decision, customer-call synthesis, writing-filter, Tuesday-9am triage',
      'ResumeReading pill on landing (localStorage-driven)',
      'Substack subscribe iframe in footer',
      'Sharper "Most readers go here next" copy in chapter footer',
    ],
    receipts: [
      { label: 'Chapters', value: '24 → 30' },
      { label: 'Widgets', value: '8 → 12' },
      { label: 'Pages', value: '32 → 38' },
    ],
  },
  {
    edition: 'Edition 1',
    date: '2026-05-07',
    tagline: 'The book became an artifact.',
    shipped: [
      '24 chapters migrated from .docx into MDX (4 parallel agents, partitioned by chapter range)',
      '8 interactive widgets: StackSelector, SwarmVisualizer, CronBuilder, ModePicker, SkillComposer, ConnectorMap, PermissionSimulator, TierListBuilder',
      'Cmd-K command palette + dark theme + view transitions + reading progress bar',
      'Resources page with copy-paste vault library: CLAUDE.md skeleton, .mcp.json examples, hook scripts, SKILL templates, 5 reusable prompts',
      'Printable cheat sheet (Ch 14, @media print styled)',
      '30-day plan generator (3 intake questions → custom 30-day calendar, .ics + markdown export)',
      'Drag-and-drop tier list builder with shareable URL hash',
      'GitHub Pages deployment via Actions; live in ~50s per push',
    ],
    receipts: [
      { label: 'Source words migrated', value: '~43,000' },
      { label: 'Parallel agents in chapter migration', value: '4' },
      { label: 'Wall-clock for full Edition 1 build', value: '~3 hours' },
      { label: 'Dist size', value: '1.4 MB / 32 pages' },
    ],
  },
];
