// Auto-generated by scripts/scan-screenshots.py — do not edit by hand.
// Re-run via `npm run build` (prebuild hook) when files in public/screens/ change.

// id (basename without extension) -> filename with extension
export const SCREENSHOTS: Record<string, string> = {};

export const SCREENSHOT_COUNT = 0;
