// Auto-generated by scripts/scan-screenshots.py — do not edit by hand.
// Re-run via `npm run build` (prebuild hook) when files in public/screens/ change.

// id (basename without extension) -> filename with extension
export const SCREENSHOTS: Record<string, string> = {
  "01-killed-my-tabs-1": "01-killed-my-tabs-1.svg",
  "01-killed-my-tabs-2": "01-killed-my-tabs-2.svg",
  "02-five-tools-1": "02-five-tools-1.png",
  "04-the-vault-1": "04-the-vault-1.png",
  "04-the-vault-rick-2": "04-the-vault-rick-2.png",
  "04-the-vault-rick": "04-the-vault-rick.png",
  "06-the-swarm-1": "06-the-swarm-1.svg",
  "07-cron-1": "07-cron-1.svg",
  "08-three-doors-1": "08-three-doors-1.svg",
  "12-connectors-mcp-1": "12-connectors-mcp-1.png",
  "12-connectors-mcp-3": "12-connectors-mcp-3.png",
  "12-connectors-mcp-4": "12-connectors-mcp-4.png",
  "12-connectors-mcp-5": "12-connectors-mcp-5.png",
  "12-connectors-mcp-6": "12-connectors-mcp-6.png",
  "13-quickstart-1": "13-quickstart-1.svg",
  "15-yolo-decision-1": "15-yolo-decision-1.svg",
  "16-hooks-subagents-1": "16-hooks-subagents-1.svg",
  "21-three-modes-1": "21-three-modes-1.svg",
  "22-sessions-1": "22-sessions-1.svg",
  "24-lmarena-snapshot": "24-lmarena-snapshot.svg",
  "24-tier-list-1": "24-tier-list-1.svg",
  "25-evals-or-hope-1": "25-evals-or-hope-1.svg",
  "29-cost-economics-1": "29-cost-economics-1.png",
  "29-cost-economics-2": "29-cost-economics-2.png",
  "29-cost-economics-3": "29-cost-economics-3.png",
  "29-cost-economics-4": "29-cost-economics-4.png",
  "31-stages-1": "31-stages-1.svg",
  "37-context-files-1": "37-context-files-1.svg",
  "38-run-until-done-1": "38-run-until-done-1.svg",
  "38-run-until-done-2": "38-run-until-done-2.svg",
  "39-skills-you-should-steal-1": "39-skills-you-should-steal-1.svg",
  "claude-md-rules-1": "claude-md-rules-1.svg"
};

export const SCREENSHOT_COUNT = 32;
