#!/usr/bin/env python3
"""Scan public/screens/ and generate src/lib/screenshots.ts with the set of
available screenshot IDs. Run before build (already hooked via npm prebuild).

ID = filename without extension. Supported: .png, .jpg, .jpeg, .webp.

If you drop a new file into public/screens/, re-run `npm run build` and the
ScreenshotPlaceholder component with the matching `id` will swap from
placeholder card to real image automatically.
"""
import os, json

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SCREENS_DIR = os.path.join(REPO_ROOT, 'public', 'screens')
OUT_TS = os.path.join(REPO_ROOT, 'src', 'lib', 'screenshots.ts')

EXTS = {'.png', '.jpg', '.jpeg', '.webp', '.gif', '.avif'}

def main():
    os.makedirs(SCREENS_DIR, exist_ok=True)
    files = {}
    for entry in sorted(os.listdir(SCREENS_DIR)):
        path = os.path.join(SCREENS_DIR, entry)
        if not os.path.isfile(path):
            continue
        base, ext = os.path.splitext(entry)
        if ext.lower() in EXTS:
            files[base] = entry  # id -> filename

    js = [
        '// Auto-generated by scripts/scan-screenshots.py — do not edit by hand.',
        '// Re-run via `npm run build` (prebuild hook) when files in public/screens/ change.',
        '',
        '// id (basename without extension) -> filename with extension',
        f'export const SCREENSHOTS: Record<string, string> = {json.dumps(files, indent=2)};',
        '',
        f'export const SCREENSHOT_COUNT = {len(files)};',
    ]
    with open(OUT_TS, 'w') as f:
        f.write('\n'.join(js) + '\n')
    print(f"Wrote {OUT_TS} with {len(files)} screenshot(s).")

if __name__ == '__main__':
    main()
